### ISSUE TITLE
How about the relationship between session and kernel? 

### ISSUE THREAD

**Issue by xiangzhetianlumaijing** [jupyter-server/jupyter_server#1058]
Can multiple sessions use the same kernel? Can multiple clients share execution results through the same kernel sharer?

**Comment by Zsailer** [comment]
Yes, Jupyter Server can handle connecting multiple sessions to the same kernel. JupyterLab leverages this feature to allow multiple notebooks+consoles to connect to the same kernel. 

If you `POST` to the `/api/sessions` with a session model that includes a [`id` (kernel_id)](https://github.com/jupyter-server/jupyter_server/blob/f6b732c652e0b5a600ff0d3f60c6a34173d8d6a5/jupyter_server/services/sessions/handlers.py#L68) field for the existing kernel, the server will attach a new session to the existing kernel.

**Comment by Zsailer** [comment]
Closing this issue as "answered", but feel free to re-open if you have follow-up question around this topic. Thanks!
