### ISSUE TITLE
`GET /api/me` with body

### ISSUE THREAD

**Issue by davidbrochart** [jupyter-server/jupyter_server#1072]
## Description

I recently read in the [HTTPX documentation](https://www.python-httpx.org/compatibility/#request-body-on-http-methods) that `GET` methods "are specified as not supporting a request body".
In jupyter-server, the [GET /api/me](https://github.com/jupyter-server/jupyter_server/blob/830c87fe4879ea77d017e1200e8ef77dd546b539/jupyter_server/services/api/handlers.py#L64) route expects a body. I don't know if it's an issue?

**Comment by Zsailer** [comment]
cc @minrk

**Comment by minrk** [comment]
GET arguments don't come the body, they are in url params. That line means `GET /api/me?permissions=...`, as seen [in the tests](https://github.com/jupyter-server/jupyter_server/blob/830c87fe4879ea77d017e1200e8ef77dd546b539/tests/services/api/test_api.py#L156).
