### ISSUE TITLE
Use the Jupyter icon as avatar for the `jupyter-server-bot`

### ISSUE THREAD

**Issue by jtpio** [jupyter-server/jupyter_server#1080]
### Problem

Those following activity on the `jupyter_server` repo can see the following notification in their timeline:

![image](https://user-images.githubusercontent.com/591645/203133918-9f66702c-87ce-4172-9da5-2d2abde4bf3c.png)

In this case the bot uses a default random GitHub avatar.

### Proposed Solution

Using the Jupyter icon would make it a bit easier to parse the information in the feed and notifications.

### Additional context

Probably this could also be applied to other release bots.

**Comment by blink1073** [comment]
Good call, I did this for the JupyterLab, Jupyter Server, Jupyter, and IPython bots just now.

**Comment by jtpio** [comment]
Nice thanks!
