### ISSUE TITLE
'AsyncIOLoopKernelManager' object has no attribute 'ports_changed'

### ISSUE THREAD

**Issue by fcollonval** [jupyter-server/jupyter_server#1086]
## Description

https://github.com/jupyter-server/jupyter_server/pull/1047 introduces a new assumption on the `KernelManager` API that is not correct `kernel_manager.ports_changed` is not mandatory (it does not exist on the [abstract class](https://github.com/jupyter/jupyter_client/blob/main/jupyter_client/managerabc.py) nor on the default `jupyter_client.ioloop.AsyncIOLoopKernelManager`) :

https://github.com/jupyter-server/jupyter_server/blob/cd060da67aa6e3e5d8ff791f0a559a91282be2b3/jupyter_server/services/kernels/connection/channels.py#L336

## Reproduce

Error seen on JupyterLab CI: https://github.com/jupyterlab/jupyterlab/actions/runs/3530210941/jobs/5921960684

## Expected behavior

No error

## Reference

Version: jupyter_server-2.0.0rc6

**Comment by fcollonval** [comment]
> The call existed in the code prior to #1047 in `jupyter_server/services/kernels/handlers.py#L464`

**Comment by Zsailer** [comment]
Thanks, @fcollonval. Looks like #1047 calls `ports_changed` at the wrong level.

This has been an annoying readability issue in Jupyter Server for a long time. When JS says `kernel_manager` is usually means the Mapping/Multi Kernel Manager, not the individual Kernel Managers. in #1047, I tried to be more explicit, but looks like I got it wrong in this instance.

**Comment by fcollonval** [comment]
Thanks @Zsailer for the quick fix and thanks @blink1073 for the new release

Happy Thanksgiving to both of you
