### ISSUE TITLE
ServerApp should not write to disk if it does not need to

### ISSUE THREAD

**Issue by hhuuggoo** [jupyter-server/jupyter_server#1087]
### Problem

[We run jupyter in docker containers (like jupyterhub)](https://saturncloud.io/)  , and when users run out of disk space, their containers fail to start. This is caused by `jupyter_server` writing `browser_open_file`.

### Proposed Solution

We have worked around this problem by configuring those files to live in /tmp

```
c.ServerApp.browser_open_file = '/tmp/jp.json'
c.ServerApp.browser_open_file_to_run = '/tmp/jprun.json'
```

This is fine - but it seems like those files should not be written at all if they are not needed? Could we avoid writing those files if  `open_browser` is `False`?

I can submit the PR, but I wanted to validate that this makes sense first.

**Comment by blink1073** [comment]
Hi @hhuuggoo, `Could we avoid writing those files if open_browser is False?` sounds right to me.  A PR would be welcome!
