### ISSUE TITLE
Using `base_url` and a Jupyter Enterprise Gateway breaks kernelspec logo requests

### ISSUE THREAD

**Issue by bloomsa** [jupyter-server/jupyter_server#1111]
## Description

I have noticed that using the [ServerApp.base_url config](https://jupyter-server.readthedocs.io/en/latest/operators/public-server.html#running-the-notebook-with-a-customized-url-prefix), in conjunction with an Enterprise Gateway setup (--gateway-url) breaks the requesting of kernelspec logos. 
<img width="1804" alt="Screen Shot 2022-12-02 at 3 02 03 PM" src="https://user-images.githubusercontent.com/20909250/205385822-e7f9b9ad-ee22-446f-a8eb-0485c870be24.png">

## Reproduce

pre-req: have Jupyter Enterprise Gateway setup serving kernelspecs and resources (logos)
1. connect a JupyterLab instance to that Gateway using the following command `jupyter lab --gateway-url=https://example.com --ServerApp.base_url='anything' --debug`
2. when the JLab launcher loads, the kernel options will be there but the logos will have failed to load

I diagnosed this by trying a Lab instance with and without the `base_url` config. when running without the config, the logos load and I see the [expected debug logs](https://github.com/jupyter-server/jupyter_server/blob/7d2154a1e243f80ed5fc4c067fd022e32f3fc8f0/jupyter_server/gateway/managers.py#L284) when they are being retrieved. 
<img width="893" alt="Screen Shot 2022-12-02 at 3 09 34 PM" src="https://user-images.githubusercontent.com/20909250/205386772-8c402dcb-4ed4-4b4d-9620-76a84bfcc503.png">

As soon as I pass in the `base_url` config, so that Jupyter-server is listening on something like `localhost:8888/example/`, the kernel logos do not load, nor do I see the debug logs. That indicated to me that using the base_url in Jupyter Server is causing `GatewayKernelSpecManager.get_kernel_spec_resource` ([link](https://github.com/jupyter-server/jupyter_server/blob/7d2154a1e243f80ed5fc4c067fd022e32f3fc8f0/jupyter_server/gateway/managers.py#L271)) to never be reached. 
 
## Expected behavior

As mentioned above, I expected to see log messages indicating that the kernelspec resource methods were being ran, and that Jupyter Server was calling Jupyter Enterprise Gateway to retrieve the logo resources.
## Context

- Operating System and version: MacOS Monterey
- Browser and version: Chrome v107
- Jupyter Server version: 1.23.2

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[W 2022-12-02 15:21:40.586 ServerApp] 404 GET /kernelspecs/redacted-kernel-name/logo-64x64.png (::1) 54.12ms referer=http://localhost:8090/testing/lab/workspaces/auto-c
[D 2022-12-02 15:21:40.587 ServerApp] Using contents: services/contents
[W 2022-12-02 15:21:40.588 ServerApp] 404 GET /kernelspecs/redacted-kernel-name/logo-64x64.png (::1) 55.89ms referer=http://localhost:8090/testing/lab/workspaces/auto-c
</pre>
To me, that seems to show that JupyterLab or Jupyter Server is trying to request the exact route present in the kernelspec resources block, without prefixing it with the Server's base_url, causing the Server to throw a 404, rather than redirect out to the Enterprise Gateway
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by kevin-bates** [comment]
Hi @bloomsa - thanks for bringing this to our attention.  Is this something you'd like to contribute a fix for or leave to us? No worries either way.

**Comment by kevin-bates** [comment]
Yeah, I was just looking into this and it's a bit tricky.  You're on the right track.  The "resource" entry in the spec returned from the gateway server needs to be adjusted with the "client-server's" `base_url`.  However, _that_ entry _could_ already be "adjusted" if the gateway server itself is using a `base_url` and _that_ value would need to be replaced.

I think the places that need this change are in [`GatewayKernelSpecManager.list_kernel_specs()`](https://github.com/jupyter-server/jupyter_server/blob/53380a79276626cd6e51f6c3c9cb2aadc07e2c40/jupyter_server/gateway/managers.py#L234) and  [`GatewayKernelSpecManager.get_kernel_spec()`](https://github.com/jupyter-server/jupyter_server/blob/53380a79276626cd6e51f6c3c9cb2aadc07e2c40/jupyter_server/gateway/managers.py#L242), where each of the _values_ of the `resources` dictionary (for each kernelspec) would need their `/kernelspecs/<kernel_name>/...` entry replaced with `base-url/kernelspecs/<kernel_name>/...`.  But we also need to tolerate the gateway entry being something like `gateway-base-url/kernelspecs/<kernel_name>/...`.

(I have confirmed that when a base-url is configured for the gateway (or server) there's no leading slash so replacing the first item following `split("/")` and reassembling may be sufficient.)

**Comment by lresende** [comment]
Let's please test the solution in the context of JupyterHub with gateway-url as this have the same broken icons as well.

**Comment by kevin-bates** [comment]
Hi @lresende - I remember you raising this before in that particular context but I guess you didn't track it down.  Does Hub always launch each notebook server with a base-url (probably something associated with the launching user's name)?  Are you able to test the solution in a Hub configuration?  (I don't have one and don't really want to set one up.)

**Comment by kevin-bates** [comment]
> (I have confirmed that when a base-url is configured for the gateway (or server) there's no leading slash so replacing the first item following split("/") and reassembling may be sufficient.)

This isn't a correct statement when the `base_url` includes a leading `"/"`, so it seems using the right-most `"/kernelspecs/"` sequence as the anchor is more appropriate.

Since the pytests use a `base_url` by default (the [`jp_base_url` fixture](https://github.com/jupyter-server/pytest-jupyter/blob/cad7bc80c8cd1baa3e1162258e93c66f214f55fa/pytest_jupyter/jupyter_server.py#L278-L281) defaults to `"/a%40b/"`) I think we could add support to test this by setting the appropriate values [here](https://github.com/jupyter-server/jupyter_server/blob/53380a79276626cd6e51f6c3c9cb2aadc07e2c40/tests/test_gateway.py#L48) and validating that  fetched kernelspecs reference start with the `jp_base_url`.

**Comment by bloomsa** [comment]
I'm working on a fix for this now, but I had a question. Should I base my fork off of the main branch here, even though EG only supports Jupyter-server < 2.0 right now? If yes, it'd have to be back-ported for it to flow into existing EG-enabled systems.
