### ISSUE TITLE
Extension for POST Execute cell

### ISSUE THREAD

**Issue by Wh1isper** [jupyter-server/jupyter_server#1123]
### Problem

Jupyter has been plaguing us with the problem of saving code output using the front-end for too long. 

There is a lot of discussion about this here

https://github.com/jupyterlab/jupyterlab/issues/12455
https://github.com/jupyterlab/jupyterlab/issues/12867
https://github.com/jupyterlab/jupyterlab/issues/2833
https://github.com/jupyter/notebook/issues/641

### Proposed Solution

Thanks to contributors, with JupyterLab 4.0 using y-crdt related features, we already have the ability to read changes from files, and the next step is to let the Jupyter server take over the responsibility of writing code execution results.

To validate this idea, I implemented a simple generic client based on the websocket interface (I tried using `jupyter_client`'s zmq interface, but it was hard to use), and then implemented a plugin with fileid support to implement this functionality.

client: https://github.com/Wh1isper/jupyter_kernel_client
extension: https://github.com/Wh1isper/jupyter_kernel_executor

Time is short, there is still a lot of content not perfect, looking forward to your suggestions 

### Additional context

I was inspired by the following projects and issues

https://github.com/jupyter-server/jupyter_server/issues/900

https://github.com/jupyter-server/jupyverse/
https://github.com/jupyter-server/jupyter_server_fileid
https://github.com/jupyter/nbformat

**Comment by Wh1isper** [comment]
https://user-images.githubusercontent.com/43375501/206643689-da95cdad-8e14-4b6a-bde2-cc452abcf399.mp4

**Comment by Wh1isper** [comment]
![jupyterlab-co-ex](https://user-images.githubusercontent.com/43375501/206644147-3d3d0a36-6bf3-4dbf-98bd-f7ca6233ebe4.gif)

**Comment by gogobd** [comment]
This looks very promising, thank you for your work!

**Comment by Wh1isper** [comment]
Sorry guys, I don't have time to work on Jupyter related things anymore due to a change in work.

I've put my thoughts here, and you can also use the same issue to get an idea of what the Jupyter-server project team is doing at the moment.

I'll keep an eye on the this in my spare time, feel free to invite me to any relevant discussions as well.

Issue: https://github.com/jupyter-server/jupyter_server/issues/1274
My comment: https://github.com/jupyter-server/jupyter_server/issues/1274#issuecomment-1657944667

Thank you all!
