### ISSUE TITLE
2.0.1: break showHiddenFiles in JupyterLab UI

### ISSUE THREAD

**Issue by tarrade** [jupyter-server/jupyter_server#1129]
## Description

When switching from `jupyter_server=1.23.3` to ` jupyter_server=2.0.1`, in JupyterLab, I don't see anymore hidden files.

## Reproduce

I am using:
` jupyter_server=2.0.1`
`jupyterlab=3.5.1`

and the following standard setup to see hidden file in JupyterLab:

```
{
    // File Browser
    // @jupyterlab/filebrowser-extension:browser
    // File Browser settings.
    // *****************************************

    // Show hidden files
    // Whether to show hidden files
    "showHiddenFiles": true
}
```

and:
`c.ContentsManager.allow_hidden = True`

## Expected behavior

I am expecting to have the same UI and feature as with `jupyter_server=1.23.3` as below
[Expecting UI](https://i.stack.imgur.com/8X5Ry.pngl)

## Context
- Operating System and version: Ubuntu 20.04.5 LTS
- Browser and version: Google Chrome Version 108.0.5359.99 (Official Build) (64-bit)
- Jupyter Server version: 2.0.1

<details><summary>Troubleshoot Output</summary>
<pre>
Not sure I saw some meaningful information in the logfile because of other issues related to new jupyter_server like jupytext, jupyterlab-git
</pre>
</details>

**Comment by tarrade** [comment]
I managed to find some error in the log after some other issues got fixed (JupyterLab extension).
```
[ServerApp][m 500 PUT /lab/api/settings/@jupyterlab/filebrowser-extension:browser?1671117244643 (172.17.0.1): Failed writing settings (@jupyterlab/filebrowser-extension:browser): [Errno 13] Permission denied: '/opt/conda/envs/jupyter-notebook/etc/jupyter/lab'
[LabApp][m wrote error: "Failed writing settings (@jupyterlab/filebrowser-extension:browser): [Errno 13] Permission denied: '/opt/conda/envs/jupyter-notebook/etc/jupyter/lab'"
```

My setup is the same as for `jupyter_server=1.23.3`

I have a conda env in this location:
```
jupyter@:/opt/conda/envs/jupyter-notebook/etc/jupyter$ ls
jupyter_config.json  jupyter_notebook_config.d  jupyter_server_config.d  nbconfig
```
as you can see there is no folder called "/lab" 

The ServerApp should be looking here:

**Comment by blink1073** [comment]
Hi @tarrade, I believe this is related to https://github.com/jupyter/jupyter_core/pull/323.  For now you can set `JUPYTER_PREFER_ENV_PATH=0`.

**Comment by tarrade** [comment]
@blink1073 yes, this works for me. Thanks.

**Comment by tarrade** [comment]
I guess another cosmetic impact of the current default setup is that now kernel got a suffix "(Local)".

Before:
` Python [conda env:jupyter-notebook]`

Now:
` Python [conda env:jupyter-notebook] (Local)`

```

It is not coming from the kernel.json which is identical

**Comment by kevin-bates** [comment]
> I guess another cosmetic impact of the current default setup is that now kernel got a suffix "(Local)".

It looks like you're using [`nb_conda_kernels`](https://github.com/Anaconda-Platform/nb_conda_kernels), which is responsible for [_generating_ the kernel's display name](https://github.com/Anaconda-Platform/nb_conda_kernels/blob/f461d2159a970fec323f0c225557e74c63c6a45b/nb_conda_kernels/manager.py#L236-L250).  Might you have [`name_format` configured](https://github.com/Anaconda-Platform/nb_conda_kernels/blob/f461d2159a970fec323f0c225557e74c63c6a45b/nb_conda_kernels/manager.py#L60) to something that includes (or generates) `"(Local)"`?

Can you provide the content of `kernel.json` and the name of the directory in which it resides (as that is considered the `kernel_name`)? 

Regardless, I suspect you'd need to take this particular issue up with the `nb_conda_kernels` folks.

**Comment by tarrade** [comment]
Hi @kevin-bates ,

yes, I am using [nb_conda_kernels](https://github.com/Anaconda-Platform/nb_conda_kernels) which didn't change since sept 2020 (I only changed the jupyter_server version). My `kernel.json` doesn't contain "(Local)" but the following:

```
cat /opt/conda/envs/jupyter-notebook/share/jupyter/kernels/python3/kernel.json 
{
 "argv": [
  "/opt/conda/envs/jupyter-notebook/bin/python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3 (ipykernel)",
 "language": "python",
 "metadata": {
  "debugger": true
 }
```

it seems that the bad display is now gone after I introduced all the following:
```
export JUPYTER_CONFIG_DIR="/home/jupyter/.jupyter"
export JUPYTER_DATA_DIR="/home/jupyter/.local/share/jupyter"
export JUPYTER_RUNTIME_DIR="/home/jupyter/.local/share/jupyter"
## Jupyter server setup 2.0
export JUPYTER_PREFER_ENV_PATH=0
```

It seems to be related to https://github.com/jupyter/jupyter_core/pull/324 and  https://github.com/jupyter/jupyter_core/pull/323.

On my side this is all good.

**Comment by tarrade** [comment]
@blink1073 do I get it right that I could use `jupyter_core v5.1.1 `without `JUPYTER_PREFER_ENV_PATH=0` and it should work in the same way as before ? Thanks

**Comment by blink1073** [comment]
Yes, it should work now, please let us know either way!

**Comment by tarrade** [comment]
@blink1073 @kevin-bates I confirm that using solved all previous issues mention in this tread. I am using:
`jupyter_core 5.1.1`  and ` jupyter_server  2.0.5 `

No need of the following anymore:
```
export JUPYTER_CONFIG_DIR="/home/jupyter/.jupyter"
export JUPYTER_DATA_DIR="/home/jupyter/.local/share/jupyter"
export JUPYTER_RUNTIME_DIR="/home/jupyter/.local/share/jupyter"
export JUPYTER_PREFER_ENV_PATH=0
```

Here the jupyter depedencies. I had to use `pypi` for jupyter-core as it was not (yet)available with `conda-forge`
```
# packages in environment at /opt/conda/envs/jupyter-notebook:
jupyter-core              5.1.1                    pypi_0    pypi
jupyter-server-mathjax    0.2.6                    pypi_0    pypi
jupyter_client            7.4.8           py310h06a4308_0    defaults
jupyter_events            0.5.0              pyhd8ed1ab_1    conda-forge
jupyter_server            2.0.5              pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.3              pyhd8ed1ab_0    conda-forge
jupyterlab                3.5.2              pyhd8ed1ab_0    conda-forge
jupyterlab-git            0.41.0                   pypi_0    pypi
jupyterlab_pygments       0.1.2                      py_0    defaults
jupyterlab_server         2.16.3          py310h06a4308_0    defaults
jupyterlab_widgets        3.0.4              pyhd8ed1ab_0    conda-forge
```

Thanks for the help and all the fixes. Closing

**Comment by blink1073** [comment]
Fantastic, thanks again for the report and follow up!
