### ISSUE TITLE
UserWarning recommends accessing URL for help that does not exist

### ISSUE THREAD

**Issue by johncoxon** [jupyter-server/jupyter_server#1164]
## Description

When running `jupyter notebook` I get `UserWarning: The Tornado web application does not have an 'identity_provider' defined in its settings. In future releases of jupyter_server, this will be a required key for all subclasses of `JupyterHandler`. For an example, see the jupyter_server source code for how to add an identity provider to the tornado settings: https://github.com/jupyter-server/jupyter_server/blob/aa8fd8b3faf37466eeb99689d5555314c5bf6640/jupyter_server/serverapp.py#L253`. The URL mentioned in this warning does not exist and so I don't understand how to fix this issue.

## Reproduce

1. Run `jupyter notebook`.

## Expected behavior

I expect the `UserWarning` to provide useful information on how to fix the issue triggering the warning.

## Context

- Operating System and version: macOS 13.0.1
- Browser and version: Microsoft Edge 108.0.1462.54 (Official build) (arm64)
- Jupyter Server version: Jupyter Notebook 6.5.2

When I include the output requested, GitHub complains that the comment is too long. I can provide the output of `jupyter troubleshoot` and `jupyter lab --debug` separately if it's necessary.

**Comment by rscircus** [comment]
+1

**Comment by krassowski** [comment]
I believe that this was fixed over two years ago in https://github.com/jupyter-server/jupyter_server/pull/1158 - you must be running an old version. If you still see this issue in the latest jupyter-server version (currently v2.14.2) please reopen or leave a comment with your version number.

**Comment by rscircus** [comment]
![image](https://github.com/user-attachments/assets/810552d9-3807-4b85-8959-e2ec032bf6b4)
