### ISSUE TITLE
Propagate Enterprise Gateway Error Messages to Frontend Users

### ISSUE THREAD

**Issue by broden-wanner** [jupyter-server/jupyter_server#1231]
### Problem

Currently, Jupyter Server is sending a generic error message to the frontend (e.g. Jupyter Lab) when Enterprise Gateway returns an error code to Jupyter Server. For instance, when kernel creation fails because of a timeout, this message is displayed to the user in Jupyter Lab:

![image](https://user-images.githubusercontent.com/30425158/223227129-c971d706-46e7-4c3b-bab1-984a82b90913.png)

- Error message in text: `HTTP 500: Internal Server Error (Error attempting to connect to Gateway server url 'https://mygatewayurl'. Ensure gateway url is valid and the Gateway instance is running.)`

I've verified that the url is correct and Enterprise Gateway is running. When I look at the logs for Enterprise Gateway, I see this message:

```
[E 2023-03-06 20:15:32.234 EnterpriseGatewayApp] KernelID: 'c69863ff-e5d8-49bc-8224-55029087d6d5' launch timeout due to: Waited too long (40.0s) to get connection file
[E 230306 20:15:32 web:2239] 500 POST /api/kernels (127.0.0.1) 40516.19ms
```

I would like this message or something similar to be propagated to the user on the frontend (an error message saying something along the lines of "Kernel creation failed: launch timeout") instead of showing the user a generic error message like is the current behavior. Enterprise Gateway does send back an error message to Jupyter Server, but I see in the `jupyter_server/gateway/gateway_client.py` code that any error body returned from Enterprise Gateway is disregarded and the error message I showed above is returned ([link to relevant code](https://github.com/jupyter-server/jupyter_server/blob/d85874b0d6ad16c8797bb99425b0282dea33630b/jupyter_server/gateway/gateway_client.py#L730-L735)). 

All in all, I would like the error returned in the payload from Enterprise Gateway to be shown to the user or at least an approximation of the error message to be shown to the user.  Having a descriptive error message for the user would help our team with debugging these kernel creation errors and lets users know whether or not retrying kernel creation could succeed. We have a custom resource manager for Enterprise Gateway that can be finicky sometimes, so having these error messages shown to the user would also streamline our development of the custom resource manager. 

### Proposed Solution

Change the [gateway_request](https://github.com/jupyter-server/jupyter_server/blob/d85874b0d6ad16c8797bb99425b0282dea33630b/jupyter_server/gateway/gateway_client.py#L720-L756) function's error handling behavior to embed Enterprise Gateway's error message into the exception `tornado.web.HTTPError` that is raised when Enterprise Gateway returns an error and also log the error to the console where Jupyter Server is running. A rough idea of this would be the following:
```python
async def gateway_request(endpoint: str, **kwargs: ty.Any) -> HTTPResponse:
    """Make an async request to kernel gateway endpoint, returns a response"""
    kwargs = GatewayClient.instance().load_connection_args(**kwargs)
    rhc = RetryableHTTPClient()
    try:
        response = await rhc.fetch(endpoint, **kwargs)
    except HTTPClientError as e:
        # Load the error payload from Enterprise Gateway
        error_payload = json.loads(e.response.body)
        raise web.HTTPError(
            e.code,
            f"Error from Gateway: {e.message} {error_payload['reason']}.  "  # Add the error reason to the error message
            "Contact support if the issue persists.",
        ) from e
    # Other except clauses here...

    return response
``` 

### Additional context

- Operating System and version: MacOS Ventura 13.2
- Browser and version: Chrome v109
- Jupyter Server version: 1.23.6
- Relevant Discussion on Jupyter community forum: https://discourse.jupyter.org/t/propagating-enterprise-gateway-error-messages-to-the-frontend-e-g-jupyter-lab/18293

**Comment by lresende** [comment]
Fixed by #1233
