### ISSUE TITLE
datetime.datetime.utcnow() and datetime.datetime.utcfromtimestamp() are deprecated in Python 3.12

### ISSUE THREAD

**Issue by befeleme** [jupyter-server/jupyter_server#1296]
## Description

datetime.datetime.utcnow() and datetime.datetime.utcfromtimestamp() are deprecated in Python 3.12
jupyter-server wraps them in the module `_tz.py` to contain the `tzinfo=UTC`.

Deprecation warnings say:

```
DeprecationWarning: datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.now(datetime.UTC).

DeprecationWarning: datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.fromtimestamp(timestamp, datetime.UTC)
```

Test suites of projects, which treat warnings as errors, like jupterlab-server, start failing with Python 3.12.

## Reproduce

We observed this behavior when building jupyter-server and other jupyterlab stack components as RPM in Fedora Linux 39.

## Expected behavior

Using of the module does not produce the warnings

## Context

- Operating System and version: Fedora Linux 39
- Jupyter Server version: 2.6.0

**Comment by minrk** [comment]
I think datetime.now(tzinfo=utc) is the right way now?

**Comment by blink1073** [comment]
I believe so, yes: https://docs.python.org/3.12/library/datetime.html?highlight=utcnow#datetime.datetime.now

And also: `datetime.fromtimestamp(timestamp, tz=utc)`:

https://docs.python.org/3.12/library/datetime.html?highlight=utcnow#datetime.datetime.fromtimestamp

**Comment by tornaria** [comment]
The following works for me:
```diff
--- a/jupyter_server/_tz.py
+++ b/jupyter_server/_tz.py
@@ -5,7 +5,7 @@ Just UTC-awareness right now
 """
 # Copyright (c) Jupyter Development Team.
 # Distributed under the terms of the Modified BSD License.
-from datetime import datetime, timedelta, tzinfo
+from datetime import datetime, timedelta, tzinfo, timezone
 
 # constant for zero offset
 ZERO = timedelta(0)
@@ -39,6 +39,12 @@ def utc_aware(unaware):
 utcfromtimestamp = utc_aware(datetime.utcfromtimestamp)
 utcnow = utc_aware(datetime.utcnow)
 
+def utcnow() -> datetime:
+    """ Return timezone-aware UTC timestamp"""
+    return datetime.now(timezone.utc)
+
+def utcfromtimestamp(timestamp):
+    return datetime.fromtimestamp(timestamp, timezone.utc)
 
 def isoformat(dt):
     """Return iso-formatted timestamp
--- a/tests/test_gateway.py
+++ b/tests/test_gateway.py
@@ -78,7 +78,7 @@ omitted_kernels: Dict[str, bool] = {}
 
 def generate_model(name):
     """Generate a mocked kernel model.  Caller is responsible for adding model to running_kernels dictionary."""
-    dt = datetime.utcnow().isoformat() + "Z"  # noqa
+    dt = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")  # noqa
     kernel_id = str(uuid.uuid4())
     model = {
         "id": kernel_id,
```

Note: I also had to patch tornado with https://github.com/tornadoweb/tornado/pull/3288 and https://github.com/tornadoweb/tornado/pull/3335.
