### ISSUE TITLE
kernel_actions/v1 spec expects field that is not available

### ISSUE THREAD

**Issue by allstrive** [jupyter-server/jupyter_server#1299]
## Description
When Enterprise Gateway fails to create a kernel for the jupyter notebook, the response is not expected to contain any kernel ID. However, the kernel_actions/v1.yaml expects that kernel_id be present. The error response results in subsequent event validation error due to kernel_id that is set to None.

## Reproduce

1. Try to launch a Gateway Kernel with spec that would gurantee failure
2. When Gateway client fails - it generates subsequent validation error
3. Expected event is not generated as a result

## Expected behavior
When the Gateway fails to launch kernel it should also log that as an event

## Context

- Operating System and version: Not relevant
- Browser and version: Not relevant
- Jupyter Server version: Not relevant
- Jupyter-Server version : 2.7.0

<details><summary>Troubleshoot Output</summary>
<pre>

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>

</pre>
</details>

<details><summary>Browser Output</summary>

<pre>

</pre>
</details>

**Comment by kevin-bates** [comment]
This condition is not exclusive to the use of a gateway - correct?  _Any_ failure of a kernel's start will not (necessarily) have a kernel_id present and, as a result, violate the event schema's validation.  I just want to make sure my understanding is correct and it's just less common for _local_ start failures to occur (although it could be easily simulated by, for example, invalidating the `argv` stanza's content in the kernel.json file).

**Comment by allstrive** [comment]
Yes, that's correct .

**Comment by Zsailer** [comment]
Solved by https://github.com/jupyter-server/jupyter_server/pull/1300
