### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by Hind-M** [jupyter-server/jupyter_server#1304]
The link used [here](https://github.com/jupyter-server/jupyter_server/blob/main/docs/source/developers/extensions.rst?plain=1#L583) is broken.
I would be happy to send a PR but I am not sure what to put instead.
https://jupyter-notebook.readthedocs.io/en/stable/extending/ maybe?

**Comment by blink1073** [comment]
Hi @Hind-M, yes, please!  Since Notebook 7 uses Jupyter Server now, we can use https://jupyter-notebook.readthedocs.io/en/v6.5.4/extending/handlers.html.
