### ISSUE TITLE
Latest release is breaking custom ContentManager

### ISSUE THREAD

**Issue by fcollonval** [jupyter-server/jupyter_server#1366]
## Description

https://github.com/jupyter-server/jupyter_server/pull/1363 changed the `ContentManager` API in a breaking manner; this can be seen in https://github.com/mwouts/jupytext/issues/1165
But I hit it too on private code.

## Reproduce

Install jupytext

## Expected behavior

The content manager get should be called without md5 if it does not support it.

## Context

- Jupyter Server version: 2.11.0

<details><summary>Command Line Output</summary>
<pre>
 TypeError: build_jupytext_contents_manager_class.<locals>.JupytextContentsManager.get() got an unexpected keyword argument 'md5'
</pre>
</details>

**Comment by marr75** [comment]
This also impacts the [ploomber](https://github.com/ploomber/ploomber] project.

It's disappointing that a breaking change was introduced without a major version or that an interface change that was non-breaking was not devised.

**Comment by blink1073** [comment]
I yanked 2.11.0.  Please let's keep the tone civil, we're all volunteers doing our best, the breaking API change was unintentional.

**Comment by Wh1isper** [comment]
Sorry for the breaking changes to the API. I have created https://github.com/jupyter-server/jupyter_server/pull/1367 to fix this.

**Comment by m-rossi** [comment]
I also created a PR to mark the conda-forge-package as broken: https://github.com/conda-forge/admin-requests/pull/864
