### ISSUE TITLE
Enable EPUB and HTML outputs from the docs

### ISSUE THREAD

**Issue by Zsailer** [jupyter-server/jupyter_server#1378]
This was mentioned in[ last week's Jupyter Server call ](https://github.com/jupyter-server/team-compass/issues/45#issuecomment-1866537230) by @bollwyvl 

Opening an issue track here.

**Comment by bollwyvl** [comment]
Boop! https://github.com/jupyter-server/jupyter_server/pull/1379 No rush on this, of course.
