### ISSUE TITLE
Missing Python target version bound leads to incorrect `ruff` suggestions

### ISSUE THREAD

**Issue by krassowski** [jupyter-server/jupyter_server#1394]
## Description

The lower bound Python version for jupyter-server is 3.8:

https://github.com/jupyter-server/jupyter_server/blob/8c963a19d352c162374e681234543453363bb33b/pyproject.toml#L24

This is correctly specified for `mypy`:

https://github.com/jupyter-server/jupyter_server/blob/8c963a19d352c162374e681234543453363bb33b/pyproject.toml#L272-L273

but not for `ruff`:

https://github.com/jupyter-server/jupyter_server/blob/8c963a19d352c162374e681234543453363bb33b/pyproject.toml#L142-L149

We need to add `target-version = "py38"` because right now it suggests things which would break on 3.8, such as:

```
jupyter_server/serverapp.py:532:76: UP006 Use `type` instead of `t.Type` for type annotation
```

**Comment by krassowski** [comment]
Actually, this one works due to `from __future__ import annotations` so maybe it is fine?

**Comment by blink1073** [comment]
ruff honors the python_requires field

**Comment by krassowski** [comment]
Thank you and sorry for the noise!
