### ISSUE TITLE
Stop / unload / cleanup hook for a server extension

### ISSUE THREAD

**Issue by jtpio** [jupyter-server/jupyter_server#241]
Is there currently a way for a server extension (that would run alongside other server extensions) to provide a stop / unload / cleanup hook, that would be called when the main server app is terminated (potentially in the [stop](https://github.com/jupyter/jupyter_server/blob/f1df254e17854aecb0ef025a5891c6910c62fd70/jupyter_server/serverapp.py#L1986) method)?

It looks like one way to achieve this would be for an `ExtensionApp` to define the [`ExtensionApp.stop()`](https://github.com/jupyter/jupyter_server/blob/f1df254e17854aecb0ef025a5891c6910c62fd70/jupyter_server/extension/application.py#L387-L391) method. Although this might be dedicated to extension apps started as standalone extensions?

As an example use case, a server extension could allocate extra resources that would need to be cleaned up when the app is stopped.

For example an `ExtensionApp` might want to instantiate a separate `MappingKernelManager` to keep a set of kernels isolated from the default kernel manager (this is currently explored in https://github.com/voila-dashboards/voila/pull/41 and also discussed in https://github.com/jupyter/jupyter_server/issues/235).
Having a separate kernel manager would require calling the `shutdown_all` method to make sure the kernel processes are terminated.

**Comment by oliver-sanders** [comment]
Looks like the `ExtensionApp` now has a `stop` method, however, it is for shutting down the server from the extension rather than shutting down the extension from the server:

https://github.com/jupyter-server/jupyter_server/blob/3343101cd97b587c580adc75ec27c6047ab86f30/jupyter_server/extension/application.py#L419-L423
