### ISSUE TITLE
Could not open static file ''

### ISSUE THREAD

**Issue by afshin** [jupyter-server/jupyter_server#267]
The JupyterLab [file browser example application](https://github.com/jupyterlab/jupyterlab/tree/master/examples/filebrowser) builds and launches and runs, but it occasionally (not every time) logs a `ServerApp` error that says `Could not open static file ''`

It does not appear to hurt the functioning of the application.

<img width="708" alt="Screen Shot 2020-08-06 at 17 46 24" src="https://user-images.githubusercontent.com/159529/89559827-17e13b80-d80e-11ea-91a9-d3c92155fbc7.png">

**Comment by echarles** [comment]
I will do a pass on the jlab examples this weekend and look at that. The strange thing is that it does not do log the error every time.

**Comment by Zsailer** [comment]
I'm having a hard time reproducing this, too. I'll do some digging...

**Comment by Zsailer** [comment]
Also, I think the warning about the favicon is coming from #266.

**Comment by echarles** [comment]
Tried to replicate the issue but can not get the error log. Ideas to get more details

- Does the error show up when you run `jupyter lab --no-browser` (for the no-browser to work, you need to pull latest master and reinstall as it depends also on a new jupyter_server release made yesterday).
- Do you see any error in your browser in the `Network` tab inspector?

**Comment by Zsailer** [comment]
I think this issue has gone away (though I'm not sure what was exactly fixed the issue). Closing for now; we can reopen if the issue resurfaces.
