### ISSUE TITLE
Is pywin32 actually used?

### ISSUE THREAD

**Issue by mattip** [jupyter-server/jupyter_server#281]
`setup.py` has a line to install [pywin32](https://github.com/jupyter/jupyter_server/blob/master/setup.py#L55) which is a huge package of c-extensions that does not work with PyPy. Is it actually required for jupyter_server?

**Comment by kevin-bates** [comment]
Correct - there was a bit of a migration exercise a while ago and this last step was not performed on this repo.  `jupyter_core` should be used for this and setup.py should be updated to not include this dependency.  There are a number of functions in utils.py that should get pulled from jupyter_core as well (e.g.. `is_hidden()`) and their usages updating accordingly - nice catch.

Would you be interested in making these changes?

**Comment by bollwyvl** [comment]
Can concur that this would help downstream packaging, and that we should strive to keep this package's dependencies as cross-platform as possible for as long as possible. Perhaps:
- on the 1.x line 
  - provide shim imports in utils for everything that was moved from `jupyter_core`
  - add a deprecation warning 
- drop entirely on 2.x

**Comment by stonebig** [comment]
version 2 seems far far way , could the jupyter-core simplification be anticipated a bit ?

**Comment by kevin-bates** [comment]
I think that all that needs to happen is the dependency gets dropped from `setup.cfg`.  The dependent methods were moved to jupyter_core via https://github.com/jupyter-server/jupyter_server/pull/382 but I failed to follow up on the removal of `pywin32`.  I'll submit a PR for this.
