### ISSUE TITLE
Jupyter server vs Tornado Web Server in Jupyter Notebook

### ISSUE THREAD

**Issue by mwakaba2** [jupyter-server/jupyter_server#323]
Hi, 

I'd like to learn more about the differences between the Jupyter server and the tornado web server in Jupyter notebook.
Could you elaborate the benefits for switching to the jupyter server?

For more context, my team and I maintain a Jupyterlab web application (version 1.2.x), and we're using the tornado webserver. We have a custom contents manager, and for performance improvements, we'd like to return Futures from the custom methods because they involve slow external API calls. We created a github issue in the jupyter/notebook repo: [GenericCheckpointsMixin should consider Futures returned from contents manager?](https://github.com/jupyter/notebook/issues/5752), and was wondering if there are benefits to switching to jupyter_server first and then requesting changes here instead. We're planning to upgrade to the latest Jupyterlab version.

**Comment by kevin-bates** [comment]
Hi @mwakaba2,

Jupyter server _is_ a Tornado Web Server that serves the REST API (and python classes) used by browser-based front-ends (and server-based extensions).  It is essentially equivalent to the Jupyter Notebook server without the front-end.   Jupyter Lab is intended to be the primary front-end but there is also an [NBClassic extension](https://github.com/jupyterlab/nbclassic) to provide the look and feel of today's classic Notebook UI.  In addition, I believe Lab is producing a "single-document mode" that also renders a _trimmed down_ user experience - similar to what you'd find in Notebook.

The idea behind Jupyter Server is that it becomes the primary _server_ and incorporates the necessary updates for improving performance and user experience in general.  I would certainly include an update of the Contents Manager python API to be async-tolerant as one of those "necessary updates".  We hold [weekly team meetings](https://github.com/jupyter/jupyter_server#team-meetings-and-roadmap) and I think this would be a great topic for discussion.

Per the [notice in Jupyter Notebook's README](https://github.com/jupyter/notebook#notice), we plan on transitioning focus to Jupyter Lab/Server while maintaining Notebook essentially at its current level of functionality.

**Comment by Zsailer** [comment]
Great question, @mwakaba2! Thank you for opening here. 😃 

@kevin-bates great answer :+1: . Jupyter_server started as a **fork** of Jupyter Notebook's tornado web server, has evolved slightly to help ease the transition from Notebook-->Jupyter Server, and (hopefully) will continue to evolve as Jupyter's needs grow and evolve. 

> We're planning to upgrade to the latest Jupyterlab version.

JupyterLab's next release, 3.0 (currently in RC), depends entirely on Jupyter Server. This means, you'll want to submit your changes here if you want your feature reflected in JupyterLab moving forward. As Kevin mentioned, you can also run classic Jupyter Notebook on Jupyter Server using NBClassic.

**Comment by mwakaba2** [comment]
@kevin-bates @Zsailer Thanks for the clarification!  🙂
I'll see if I can join one of the weekly meetings to discuss making Contents Manager python API async-tolerant.
Do you know roughly when 3.0 will be available?

**Comment by kevin-bates** [comment]
Here's the issue tracking the Lab 3.0 release: https://github.com/jupyterlab/jupyterlab/issues/8038.  Looks like there are a couple of outstanding issues still remaining.
