### ISSUE TITLE
[BUG] opening files with absolute paths on windows

### ISSUE THREAD

**Issue by Zsailer** [jupyter-server/jupyter_server#34]
See PR [#5051](https://github.com/jupyterlab/jupyterlab/issues/5051) in the JupyterLab repo. 

Files can be opened on Windows using absolute paths. **This shouldn't be allowed.** (It doesn't work on linux).

We should check that the jupyter server (and the classic notebook server) is not allowing absolute paths on Windows.

**Comment by blink1073** [comment]
Fixed by #1162
