### ISSUE TITLE
Repository name

### ISSUE THREAD

**Issue by lresende** [jupyter-server/jupyter_server#356]
Should we actually rename the repo to `jupyter-server`?

**Comment by Zsailer** [comment]
We briefly discussed this at a previous jupyter-server meeting. There wasn't any strong opinions expressed one way or the other. Changing the `_` to `-` doesn't cause any issues for github or PyPI, so I'm fine with it. I think it would look better in the URL 😃

**Comment by goanpeca** [comment]
For aesthetic reasons it makes sense :)

**Comment by Zsailer** [comment]
A counter argument might be that the repo name should match the Python package name which uses an `_`, i.e. `jupyter_server`.

**Comment by Zsailer** [comment]
This was discussion in the server meeting today. It was decided to keep the repo name as-is since it matches the Python package name. Closing here, but feel free to repoen if further points come up.
