### ISSUE TITLE
Replace local secure_write method with jupyter core's

### ISSUE THREAD

**Issue by kevin-bates** [jupyter-server/jupyter_server#381]
When the `secure_write` machinations were taking place, we added an implementation to jupyter_server before it found its final resting place in jupyter_core.  The second half of this [notebook issue comment](https://github.com/jupyter/notebook/issues/4937#issuecomment-759005359) exposed that its replacement was never followed up.  We'll track its replacement via this issue.

**Comment by Zsailer** [comment]
Ah, yes. This was started in #357, but closed later.

**Comment by kevin-bates** [comment]
Ok.  Thanks for the pointer.  This lead to using core's versions of `is_hidden`, `is_file_hidden`, and `exists` as well.  PR on its way.
