### ISSUE TITLE
MappingKernelManager.start_kernel should use kernel_id for new kernel if it doesn't exist

### ISSUE THREAD

**Issue by vidartf** [jupyter-server/jupyter_server#403]
The docstring of `MappingKernelManager.start_kernel` says:

https://github.com/jupyter-server/jupyter_server/blob/122d93af7cfdc777e1fe0281092c1d6cd0dd4eda/jupyter_server/services/kernels/kernelmanager.py#L170-L173

But if the kernel id doesn't currently exist, it throws an error:

https://github.com/jupyter-server/jupyter_server/blob/122d93af7cfdc777e1fe0281092c1d6cd0dd4eda/jupyter_server/services/kernels/kernelmanager.py#L202

So, the method should probably be changed to reflect the docstring (which is consistent with the behavior in jupyter client).

**Comment by kevin-bates** [comment]
Boy, this has been this way for years, but, yeah, it looks like the `if kernel_id is None:` should be extended with `or kernel_id not in self` and reflected in the args of the call to the subclass. 
 
Good catch.
