### ISSUE TITLE
Inconsistent use of _jupyter_server_extension_paths

### ISSUE THREAD

**Issue by rmorshea** [jupyter-server/jupyter_server#418]
The docs appears to use `_jupyter_server_extension_points` where `_jupyter_server_extension_paths` should have been instead:

https://github.com/jupyter-server/jupyter_server/blob/4781eecb8376a3fd2181f834f7b25c8016b11632/docs/source/developers/extensions.rst#making-an-extension-discoverable

**Comment by Zsailer** [comment]
Hey @rmorshea, thanks for opening this issue.

In jupyter_server, the function has been renamed to `_jupyter_server_extension_points` (though both will work temporarily with a [deprecation warning](https://github.com/jupyter-server/jupyter_server/blob/4781eecb8376a3fd2181f834f7b25c8016b11632/jupyter_server/extension/utils.py#L65-L70)). 

You're right, though. I did find one place in those docs where we reference `_paths` when we meant to reference `_points`. Working on a PR to correct this now.

**Comment by Zsailer** [comment]
> I did find one place in those docs where we reference _paths when we meant to reference _points

#419 corrects this issue.
