### ISSUE TITLE
terminals excluded from activity monitoring

### ISSUE THREAD

**Issue by minrk** [jupyter-server/jupyter_server#432]
Kernels are monitored for activity and can be shutdown when they have been idle for some period of time. Terminals, on the other hand, are not observed for activity and therefore never treated as idle. This has two consequences:

1. terminals cannot be shutdown by some idle timeout
2. if any terminal is started and not terminated, `shutdown_no_activity` will [never teardown the server itself](https://github.com/jupyter-server/jupyter_server/blob/bf00ad0aa27f3dcf5c9ca7c75ba42583d3a82a35/jupyter_server/serverapp.py#L1701-L1702).

This would help e.g. jupyterhub deployments that want to shutdown after some idle time.

**Comment by kevin-bates** [comment]
I think we need to port https://github.com/jupyter/notebook/pull/5372 to server (and make https://github.com/jupyter/notebook/pull/5465 is there as well).

**Comment by minrk** [comment]
Awesome! I didn't notice this had landed in the classic server already.

**Comment by kevin-bates** [comment]
We also need to bring https://github.com/jupyter/notebook/pull/5462 to the party as well.
