### ISSUE TITLE
jp_ws_fetch not work by its own

### ISSUE THREAD

**Issue by pumpkindle** [jupyter-server/jupyter_server#441]
instead of 
`async def my_test(jp_ws_fetch):`
I must use
`async def my_test(jp_ws_fetch， http_server_client)` or
`async def my_test(jp_fetch, jp_ws_fetch)` to run ws_fetch correctly, which may confuse me when I only want to test websocet

**Comment by Zsailer** [comment]
Thanks, @pumpkindle! Good catch.

Looks like a simple fix. Would you like to submit a PR to fix this?

**Comment by pumpkindle** [comment]
thx for reply, I'll have a try

**Comment by Zsailer** [comment]
Thanks, @pumpkindle! Fixed in #527.
