### ISSUE TITLE
Make passwd and passwd_check compatible with jupyter notebook

### ISSUE THREAD

**Issue by CaselIT** [jupyter-server/jupyter_server#448]
Hi,

I'm trying to configure jupyterlab to use a password. I initially created the password with `jupyter notebook password` but it does not work with jupyterlab.
After some digging I think the problem is that while jupyter notebook updated the passwd and passwd_check to use a more secure algorithm in https://github.com/jupyter/notebook/pull/3793, jupyter_server (and also ipython) did not.

Any reason not to update it here also?

Also a bit ot, how come there are 3 implementation of the same things that look identical?

**Comment by afshin** [comment]
Hi @CaselIT, we discussed this today at the server team [meeting](https://github.com/jupyter-server/team-compass/issues/4#issuecomment-802058078).  The history is that the `ipython` project split into several projects that included `jupyter notebook`.  They are now distinct products.  We should however allow `jupyter notebook` passwords to work with the `jupyter server` during a transition phase.  We agreed to detect a `jupyter notebook` password and use it if there is not one set on `jupyter server`, but warn the user.  As for jupyter/notebook#3793, we've added it to the [Running list of Notebook PRs to port](https://github.com/jupyter-server/jupyter_server/issues/110).

**Comment by CaselIT** [comment]
> The history is that the ipython project split into several projects that included jupyter notebook.  They are now distinct products.

from the outside I though it was actually all integrated, since I can use lab/notebook on the same server etc.

Thanks for the reply. Since it's already tracked in the other issue, we could close this if you prefer

**Comment by blink1073** [comment]
We can leave this open to track "allow jupyter notebook passwords to work with the jupyter server"

**Comment by afshin** [comment]
cf #450 for the port.  Regarding the backwards compat, it is already handled when using [`nbclassic`](https://github.com/jupyterlab/nbclassic), which is installed when you install JupyterLab 3.0+.

**Comment by CaselIT** [comment]
Thanks!
