### ISSUE TITLE
Tests failing with jupyter_client 6.2.0

### ISSUE THREAD

**Issue by jtpio** [jupyter-server/jupyter_server#474]
Spotted in https://github.com/jupyter-server/jupyter_server/pull/473 with this workflow:

https://github.com/jupyter-server/jupyter_server/pull/473/checks?check_run_id=2323090792#step:14:342

It looks like tests are now failing with the latest `6.2.0` release of `jupyter_client`:

![image](https://user-images.githubusercontent.com/591645/114386924-25677600-9b92-11eb-8263-8c143f626f18.png)

This also seems to be the case when re-running the jobs on master:

https://github.com/jupyter-server/jupyter_server/runs/2323188765?check_suite_focus=true#step:10:1096

**Comment by davidbrochart** [comment]
#475 should fix it.

**Comment by jtpio** [comment]
Thanks!
