### ISSUE TITLE
is there a way for the extension to cleanup?

### ISSUE THREAD

**Issue by eastonsuo** [jupyter-server/jupyter_server#544]
as far as I can see it, when a KeyboardInterrupt accur, and jupyter server runs `self._cleanup()`, which is 
```
def _cleanup(self):
        """General cleanup of files and kernels created
        by this instance ServerApp.
        """
        self.remove_server_info_file()
        self.remove_browser_open_files()
        self.cleanup_kernels()
        self.cleanup_terminals()
```
there is no way an extension can do some clean up

**Comment by Zsailer** [comment]
This should be solved by #526. Closing for now, but feel free to re-open if this PR doesn't address your needs.
