### ISSUE TITLE
Serve Directories through ServerApp.extra_static_paths

### ISSUE THREAD

**Issue by Precioussheep** [jupyter-server/jupyter_server#551]
### Problem

It would be great if a directory of static css/js files could be hosted through the “ServerApp.extra_static_paths” config, as currently it will only read the files in the directory you specify, rather than recursively hosting each folder from your specified folder down. 

For example, it would be great to specify the “static” package in the [notebook](https://github.com/jupyter/notebook) Python library as an extra path when running Jupyter lab, and server host the base sub folder (and it’s sub folders) within the that location.

### Proposed Solution

Add functionality to allow the subdirectories to be hosted when specifying paths in the “ServerApp.extra_static_paths” config.

### Additional context

<!-- Add any other context or screenshots about the feature request here. You can also include links to examples of other programs that have something similar to your request. For example:

* Another project [...] solved this by [...]

**Comment by Precioussheep** [comment]
Thanks for the response @Zsailer,

That's correct yes. Apologies if this is already possible and I've missed something.

**Comment by Zsailer** [comment]
I don't think this is something we should add to `jupyter_server` directly, but it would make a good server extension.

I would venture to guess that some deployers of Jupyter Server might not want to make the static files easily browsable by users. Making this a server extension allows a deployer to opt-in to the feature.
