### ISSUE TITLE
Slow Starting Kernels Proposal

### ISSUE THREAD

**Issue by blink1073** [jupyter-server/jupyter_server#592]
### Problem
Jupyter Notebook was originally built with the assumption that kernels would start quickly.  This turns out
to not be true for some local kernels and most remote kernels.

### Proposed Solution

  - We previously proposed changing the [REST API](https://github.com/jupyter-server/jupyter_server/issues/197) to reflect kernels/sessions that were "pending".  The downside to a REST API change is that the server would need to advertise capability through a versioned API or some other status, and clients would need to be updated to accommodate the changes.

  - An alternative method is to leave the current REST APIs intact and instead introduce the concept of a "pending" kernel that
acts like a regular kernel from the client's perspective.

  - A POST to `/api/sessions` or `/api/kernels` would create a "pending" kernel and return immediately before starting the kernel.

  - It remains to be seen during implementation what changes need to be made to handlers and managers, but at the very least we will use a [scheduled callback](https://docs.python.org/3/library/asyncio-eventloop.html#scheduling-callbacks) to actually start the kernels when we are handling the POST.
The [MappingKernelManager](https://github.com/jupyter-server/jupyter_server/blob/1a6a481acb43c34fee201cab80774ab69eab5bb6/jupyter_server/services/kernels/kernelmanager.py#L41) will also need to be updated to handle pending kernels internally in its public methods.
  - We should use the kernel manager to get the kernel id
  - We need to think about how kernel failure to start is handled for the user.  Previously, it could be given to the user in the response to a POST
  - We might even be able to add the pending logic to the handlers without needing to affect the managers (e.g by calling `save_state` on the managers directly)
  - We might also want to address slow-stopping kernels as part of these changes

**Comment by echarles** [comment]
> A POST to /api/sessions or /api/kernels would create a "pending" kernel and return immediately before starting the kernel.

For now the response to POST /api/sessions, see https://petstore.swagger.io/?url=https://raw.githubusercontent.com/jupyter/jupyter_server/master/jupyter_server/services/api/api.yaml#/sessions/post_api_sessions, is  e.g.

```
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "path": "string",
  "name": "string",
  "type": "string",
  "kernel": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "name": "string",
    "last_activity": "string",
    "connections": 0,
    "execution_state": "string"
  }
}
```

Is the intent to add an additional `status` field with value `pending` for those cases?

**Comment by blink1073** [comment]
We could make this an opt-in behavior at the level of `MultiKernelManager` in `jupyter_client`, whether to use `KernelManager` objects before waiting for them to start.  For consumers opting into this behavior, we add `.ready` property that is a future that resolves when the kernel process has started.  We may even have that wait until the "nudge" is complete.  Then, a consumer like `jupyter_server`'s websocket handler could wait for the `ready` promise before attempting to send/receive messages to the kernel.

When the opt-in behavior is selected, we do not wait for the future in [`_async_start_kernel`](https://github.com/jupyter/jupyter_client/blob/1fcf65a74a478b1de9e8c0dd238625d48b445a5f/jupyter_client/multikernelmanager.py#L189) and we instead add the kernel to our [internal map of kernels](https://github.com/jupyter/jupyter_client/blob/1fcf65a74a478b1de9e8c0dd238625d48b445a5f/jupyter_client/multikernelmanager.py#L167) immediately.

**Comment by mlucool** [comment]
This is a great idea!

We worked with @Carreau to tackle slow kernels from another angle. For remote kernels, scheduling is a somewhat large fixed cost (which this proposal seems like it'll bring down). Restarting a remote kernel need not be slow since a user typically means "restart my kernel" and not "reschedule me". With https://github.com/Carreau/inplace_restarter, you can run a restart magic to just restart the kernel, which ends up being very fast for this use case.

If other's like this idea, maybe this can be included as one way to help tackle the slow starting kernel problem for remote kernels. I understand if you feel this is far enough from the rest of this issue to warrant a separate discussion.

**Comment by blink1073** [comment]
Interesting!  Yes, I think that warrants its own discussion.  There's @echarles's recent efforts in https://github.com/datalayer/jupyterpool.
