### ISSUE TITLE
Question re requests-unixsocket dependency

### ISSUE THREAD

**Issue by lazka** [jupyter-server/jupyter_server#598]
setup.cfg lists a requests-unixsocket dependency which doesn't work on Windows but is still installed there.

https://github.com/jupyter-server/jupyter_server/blob/29be9c6658d7ef04f9b124c54102f7334b610253/setup.cfg#L45

We are trying to package this on Windows and were wondering why this dependency is needed: https://github.com/msys2/MINGW-packages/pull/9922

Looking at the the PR that added it: https://github.com/jupyter-server/jupyter_server/pull/525 it seems like it was added by accident and isn't actually used, unless I'm missing something.

**Comment by Zsailer** [comment]
Thank you for reporting, @lazka. 

You're right. As @kevin-bates mentions in https://github.com/jupyter-server/jupyter_server/pull/599, we removed the need for this dependency by refactoring the tests a bit. 

I'll merge https://github.com/jupyter-server/jupyter_server/pull/599 and cut a patch release today.

**Comment by lazka** [comment]
Thanks!

**Comment by Zsailer** [comment]
[v1.11.2](https://github.com/jupyter-server/jupyter_server/releases/tag/v1.11.2) is released with `requests-unixsocket` removed.
