### ISSUE TITLE
New websocket unable to communicate with kernel paused in debugging

### ISSUE THREAD

**Issue by kycutler** [jupyter-server/jupyter_server#622]
## Description

When establishing a new websocket connection to a kernel whose execution is paused due to debugging (e.g. paused on a breakpoint), messages sent over the websocket get no reply -- including debug requests.

## Reproduce

1. Connect to a kernel that supports debugging (e.g. IPyKernel >= 6)
2. Set a breakpoint in the kernel (e.g. using JupyterLab) and run the code so that execution is paused
3. Open a new websocket connection to the kernel
4. Notice that the websocket gets no responses, even from messages over the `control` channel.

Seems to be causing https://github.com/jupyterlab/jupyterlab/issues/10174.

Tested against different versions of `jupyter_server` and traced the issue back to version 1.1.2 (the issue does not repro in 1.1.1). This correlates with https://github.com/jupyter-server/jupyter_server/pull/361. While in this "frozen" state the console also shows that the server is nudging the kernel repeatedly, so it makes sense if this is the cause.

## Expected behavior

The kernel should still be able to communicate, at least over the `control` channel so that frontends can continue the debugger and unblock the shell.

**Comment by JohanMabille** [comment]
Fixing this requires to modify the protocol, I'm going to open a JEP for that.
