### ISSUE TITLE
how to bebug the jupyter_server source code 

### ISSUE THREAD

**Issue by pklcoder** [jupyter-server/jupyter_server#648]
I want to debug the source code of the jupyter_server ,but i do not konw how to do after run the jupyter_server\jupyter_server\__main__.py in debug  pattern.

for example:
1>i want to debug the function  to  download  a file .
i paste the url  http://localhost:8889/?token=dbf1d2c35636ababf91e57a4d0b8863ecf010f0db1668c52 then i do not know how to request  to download a file ?what is the right url?

2>i want to debug the login function but i do not know how to request the url in the browser?what is the right url?

i do as the https://jupyter-server.readthedocs.io/en/latest/contributors/contributing.html#setting-up-a-development-environment but i still do not konw how to debug the code in my local computer!
who can tell me how to debug the souce code ,thanks

**Comment by pklcoder** [comment]
Finally  i  solve this issue by my self. this  server of this version is notebook，so just add a new handler in the  notebook\notebook\services\api\handlers.py .

**Comment by Zsailer** [comment]
@pklcoder, glad to hear you were able to answer your question. 

Many of the core maintainers of this library are out on holiday, so our response time is slower than usual. 

Closing this issue for now, but feel free to re-open if the issue continues.
