### ISSUE TITLE
`jupyter_server` 1.13.2 does not work with `traitlets`  4

### ISSUE THREAD

**Issue by trungleduc** [jupyter-server/jupyter_server#661]
## Description
I got following error while using `jupyter_server` 1.13.2 with  `traitlets`  4.3.3
```shell
    from traitlets.utils.descriptions import describe
ModuleNotFoundError: No module named 'traitlets.utils.descriptions'
```

## Reproduce

```shell
mamba create -n bug python=3.9 jupyter_server=1.13.2 traitlets=4.3.3 jupyterlab
mamba activate bug
jupyter lab
```

## Expected behavior

`jupyter_server` should drop support for `traitlets` 4 in `setup.cfg`

**Comment by Zsailer** [comment]
Thanks, @trungleduc. Good catch! See #663.
