### ISSUE TITLE
Download a folder as a zip file

### ISSUE THREAD

**Issue by hadim** [jupyter-server/jupyter_server#68]
We need this feature first before implementing it in JLab/Notebook. See https://github.com/jupyter/notebook/issues/4781 for context.

**Comment by rolweber** [comment]
Sounds like a reasonable enhancement of [FilesHandler](https://github.com/jupyter/jupyter_server/blob/master/jupyter_server/files/handlers.py). But it should be configurable, in case the server admin has concerns about IO load.

**Comment by dhirschfeld** [comment]
This would be a *very* useful feature.

If you generate data (multiple files) in JupyterLab and want to get them out it's a bit painful to have to click save on each file. This is even more awkward if they are in a nested folder structure as you have to manually recreate that AFAICS.

**Comment by vidartf** [comment]
There was a proposed solution in #251 which was discussed in #252. The recommended solution is to install [jupyter-archive](https://github.com/jupyterlab-contrib/jupyter-archive).
