### ISSUE TITLE
Micro-optimization: set cache header on kernelspecs logos

### ISSUE THREAD

**Issue by mlucool** [jupyter-server/jupyter_server#702]
### Problem

kernelspecs's often contain png logos. These logos are on the order of 3kb each. Since kernels can't share a logo, each kernel contains a copy of the logo it provides. This leads to 3*number of kernels of uncached content being loaded on each page. I have ~20 kernels today, so that's 60kb being sent per refresh. (Note: this was flagged in lighthouse).

### Proposed Solution

Ideally, we'd be able to share generic logos, but since that is a bigger change, I propose we add long cache headers on logos served from `kernelspecs/<kernel>/logo-64x64.png`. Unlike the kernelspec itself, these are expected to very rarely change.

**Comment by kevin-bates** [comment]
Hi @mlucool - this seems like a great idea.  I don't know what is involved to do this, but I thought I'd point out the handler responsible for returning the logos (resources) in case you, or anyone else, would like to contribute the changes: https://github.com/jupyter-server/jupyter_server/blob/62607ce28576e50358217534161f9e7c4aab2611/jupyter_server/kernelspecs/handlers.py#L11-L32

**Comment by mlucool** [comment]
Humm, it seems the code you pointed to already uses a StaticFileHandler which sets an ETag. Lighthouse is upset that there is not Cache TTL, which should be easy enough to change.

![image](https://user-images.githubusercontent.com/1813603/155591152-7af14e4e-604a-42e7-916b-4b7f4e2df2f9.png)
