### ISSUE TITLE
Jupyter Server breaks with extensions that depend on traitlets 4

### ISSUE THREAD

**Issue by vwbusguy** [jupyter-server/jupyter_server#710]
## Description

Traitlets v4 support was removed in #661.  Unfortunately, the current code does not gracefully handle the existence of traitlets 4 and the server fails on startup.  This can happen if extensions that depend on it are installed, such as nbgrader, which [does not support traitlets v5](https://github.com/jupyter/nbgrader/issues/1447).

## Reproduce

1. From the jupyter base notebook container
2. Install nbgrader with conda
3. Enable the notebook/server extension
4. Attempt to start jupyter server

Attempted to add nbgrader to class lab container image from current Jupyter notebook base.

nbgrader was successfully installed and enabled without error.  From here, I expected Jupyter to start as it normally does.  If nothing else, the error should be handled more gracefully and preferably caught earlier on during enabling of the incompatible extension.

## Context

- Operating System and version: Ubuntu - jupyter/base-notebook:notebook-6.4.8 image
- Browser and version: Never got far enough to talk to a browser
- Jupyter Server version: jupyter/base-notebook:notebook-6.4.8
- Relevant Python deps after installing [Jupyter nbgrader](https://github.com/jupyter/nbgrader):
<pre>
Requirement already satisfied: traitlets in /opt/conda/lib/python3.9/site-packages (4.3.3)
Requirement already satisfied: six in /opt/conda/lib/python3.9/site-packages (from traitlets) (1.16.0)
Requirement already satisfied: ipython-genutils in /opt/conda/lib/python3.9/site-packages (from traitlets) (0.2.0)
Requirement already satisfied: decorator in /opt/conda/lib/python3.9/site-packages (from traitlets) (5.1.1)
</pre>

<details><summary>Troubleshoot Output</summary>
<pre>
CondaEnvException: Unable to determine environment

Please re-run this command with one of the following options:

* Provide an environment name via --name or -n
* Re-run this command inside an activated conda environment.

$PATH:
        /opt/conda/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin

sys.path:
        /opt/conda/bin
        /opt/conda/lib/python39.zip
        /opt/conda/lib/python3.9
        /opt/conda/lib/python3.9/lib-dynload
        /opt/conda/lib/python3.9/site-packages

sys.executable:
        /opt/conda/bin/python

sys.version:
        3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11) 
        [GCC 9.4.0]

platform.platform():
        Linux-4.18.0-348.12.2.el8_5.x86_64-x86_64-with-glibc2.31

which -a jupyter:
        /opt/conda/bin/jupyter

pip list:
        Package                       Version
        ----------------------------- ---------
        alembic                       1.7.6
        anyio                         3.5.0
        argon2-cffi                   21.3.0
        argon2-cffi-bindings          21.2.0
        asdf                          2.7.2
        astropy                       5.0.1
        asttokens                     2.0.5
        async-generator               1.10
        attrs                         21.4.0
        Babel                         2.9.1
        backcall                      0.2.0
        backports.functools-lru-cache 1.6.4
        black                         22.1.0
        bleach                        4.1.0
        blinker                       1.4
        Bottleneck                    1.3.4
        brotlipy                      0.7.0
        certifi                       2021.10.8
        certipy                       0.1.3
        cffi                          1.15.0
        charset-normalizer            2.0.12
        click                         8.0.4
        cloudpickle                   2.0.0
        colorama                      0.4.4
        conda                         4.11.0
        conda-package-handling        1.7.3
        coverage                      6.3.2
        cryptography                  36.0.1
        cycler                        0.11.0
        cytoolz                       0.11.2
        dask                          2022.2.1
        dataclasses                   0.8
        debugpy                       1.5.1
        decorator                     5.1.1
        defusedxml                    0.7.1
        entrypoints                   0.4
        executing                     0.8.3
        flit_core                     3.7.1
        fonttools                     4.29.1
        fsspec                        2022.2.0
        greenlet                      1.1.2
        gwcs                          0.17.1
        hypothesis                    6.39.3
        idna                          3.3
        imagecodecs                   2022.2.22
        imageio                       2.16.1
        importlib-metadata            4.11.2
        importlib-resources           5.4.0
        iniconfig                     1.1.1
        ipykernel                     6.4.2
        ipython                       7.32.0
        ipython-genutils              0.2.0
        ipywidgets                    7.6.5
        jedi                          0.18.1
        Jinja2                        3.0.3
        joblib                        1.1.0
        json5                         0.9.5
        jsonschema                    4.4.0
        jupyter                       1.0.0
        jupyter-client                7.1.2
        jupyter-console               6.4.3
        jupyter-core                  4.9.2
        jupyter-server                1.13.2
        jupyter-telemetry             0.1.0
        jupyterhub                    2.1.1
        jupyterlab                    3.2.9
        jupyterlab-pygments           0.1.2
        jupyterlab-server             2.10.3
        jupyterlab-widgets            1.0.2
        kiwisolver                    1.3.2
        libmambapy                    0.22.1
        locket                        0.2.0
        Mako                          1.1.6
        mamba                         0.22.1
        MarkupSafe                    2.1.0
        matplotlib                    3.5.1
        matplotlib-inline             0.1.3
        mistune                       0.8.4
        munkres                       1.1.4
        mypy-extensions               0.4.3
        nbclassic                     0.3.5
        nbclient                      0.5.11
        nbconvert                     5.6.1
        nbformat                      5.1.3
        nbgitpuller                   1.0.2
        nbgrader                      0.6.2
        nest-asyncio                  1.5.4
        networkx                      2.7.1
        notebook                      6.4.8
        numpy                         1.22.2
        oauthlib                      3.2.0
        packaging                     21.3
        pamela                        1.0.0
        pandas                        1.4.1
        pandocfilters                 1.5.0
        parso                         0.8.3
        partd                         1.2.0
        pathspec                      0.9.0
        pexpect                       4.8.0
        photutils                     1.3.0
        pickleshare                   0.7.5
        Pillow                        9.0.1
        pip                           22.0.3
        platformdirs                  2.5.1
        pluggy                        1.0.0
        prometheus-client             0.13.1
        prompt-toolkit                3.0.27
        psutil                        5.9.0
        ptyprocess                    0.7.0
        pure-eval                     0.2.2
        py                            1.11.0
        pycosat                       0.6.3
        pycparser                     2.21
        pycurl                        7.44.1
        pyerfa                        2.0.0.1
        Pygments                      2.11.2
        PyJWT                         2.3.0
        pyOpenSSL                     22.0.0
        pyparsing                     3.0.7
        PyQt5                         5.12.3
        PyQt5_sip                     4.19.18
        PyQtChart                     5.12
        PyQtWebEngine                 5.12.1
        pyrsistent                    0.18.1
        PySocks                       1.7.1
        pytest                        7.0.1
        pytest-arraydiff              0.3
        pytest-astropy                0.9.0
        pytest-astropy-header         0.1.2
        pytest-cov                    3.0.0
        pytest-doctestplus            0.12.0
        pytest-filter-subpackage      0.1.1
        pytest-mock                   3.7.0
        pytest-openfiles              0.5.0
        pytest-remotedata             0.3.3
        python-dateutil               2.8.2
        python-json-logger            2.0.1
        pytz                          2021.3
        PyWavelets                    1.2.0
        PyYAML                        6.0
        pyzmq                         22.3.0
        qtconsole                     5.2.2
        QtPy                          2.0.1
        rapidfuzz                     1.9.1
        requests                      2.27.1
        ruamel.yaml                   0.17.21
        ruamel.yaml.clib              0.2.6
        ruamel-yaml-conda             0.15.80
        scikit-image                  0.19.2
        scikit-learn                  1.0.2
        scipy                         1.8.0
        semantic-version              2.9.0
        Send2Trash                    1.8.0
        setuptools                    60.9.3
        six                           1.16.0
        sniffio                       1.2.0
        sortedcontainers              2.4.0
        SQLAlchemy                    1.3.23
        stack-data                    0.2.0
        terminado                     0.13.1
        testpath                      0.6.0
        threadpoolctl                 3.1.0
        tifffile                      2022.2.9
        toml                          0.10.2
        tomli                         2.0.1
        toolz                         0.11.2
        tornado                       6.1
        tqdm                          4.63.0
        traitlets                     5.0.5
        typed-ast                     1.5.2
        typing_extensions             4.1.1
        unicodedata2                  14.0.0
        urllib3                       1.26.8
        wcwidth                       0.2.5
        webencodings                  0.5.1
        websocket-client              1.3.1
        wheel                         0.37.1
        widgetsnbextension            3.5.2
        zipp                          3.7.0

conda list:
        # packages in environment at /opt/conda:
        #
        # Name                    Version                   Build  Channel
        _libgcc_mutex             0.1                 conda_forge    conda-forge
        _openmp_mutex             4.5                       1_gnu    conda-forge
        alembic                   1.7.6              pyhd8ed1ab_0    conda-forge
        alsa-lib                  1.2.3                h516909a_0    conda-forge
        anyio                     3.5.0            py39hf3d152e_0    conda-forge
        aom                       3.3.0                h27087fc_1    conda-forge
        argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
        argon2-cffi-bindings      21.2.0           py39h3811e60_1    conda-forge
        asdf                      2.7.2              pyhd8ed1ab_0    conda-forge
        astropy                   5.0.1            py39hce5d2b2_0    conda-forge
        asttokens                 2.0.5              pyhd8ed1ab_0    conda-forge
        async_generator           1.10                       py_0    conda-forge
        attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
        babel                     2.9.1              pyh44b312d_0    conda-forge
        backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
        backports                 1.0                        py_2    conda-forge
        backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
        black                     22.1.0             pyhd8ed1ab_0    conda-forge
        bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
        blinker                   1.4                        py_1    conda-forge
        blosc                     1.21.0               h9c3ff4c_0    conda-forge
        bottleneck                1.3.4            py39hd257fcd_0    conda-forge
        brotli                    1.0.9                h7f98852_6    conda-forge
        brotli-bin                1.0.9                h7f98852_6    conda-forge
        brotlipy                  0.7.0           py39h3811e60_1003    conda-forge
        brunsli                   0.1                  h9c3ff4c_0    conda-forge
        bzip2                     1.0.8                h7f98852_4    conda-forge
        c-ares                    1.18.1               h7f98852_0    conda-forge
        c-blosc2                  2.0.4                h5f21a17_1    conda-forge
        ca-certificates           2021.10.8            ha878542_0    conda-forge
        certifi                   2021.10.8        py39hf3d152e_1    conda-forge
        certipy                   0.1.3                      py_0    conda-forge
        cffi                      1.15.0           py39h4bc2ebd_0    conda-forge
        cfitsio                   4.0.0                h9a35b8e_0    conda-forge
        charls                    2.3.4                h9c3ff4c_0    conda-forge
        charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
        click                     8.0.4            py39hf3d152e_0    conda-forge
        cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
        colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
        conda                     4.11.0           py39hf3d152e_0    conda-forge
        conda-package-handling    1.7.3            py39h3811e60_1    conda-forge
        configurable-http-proxy   4.5.1           node17_h7e777a6_1    conda-forge
        coverage                  6.3.2            py39hb9d737c_1    conda-forge
        cryptography              36.0.1           py39h95dcef6_0    conda-forge
        cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
        cytoolz                   0.11.2           py39h3811e60_1    conda-forge
        dask-core                 2022.2.1           pyhd8ed1ab_0    conda-forge
        dataclasses               0.8                pyhc8e2a94_3    conda-forge
        dbus                      1.13.6               h5008d03_3    conda-forge
        debugpy                   1.5.1            py39he80948d_0    conda-forge
        decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
        defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
        entrypoints               0.4                pyhd8ed1ab_0    conda-forge
        executing                 0.8.3              pyhd8ed1ab_0    conda-forge
        expat                     2.4.6                h27087fc_0    conda-forge
        flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
        font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
        font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
        font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
        font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
        fontconfig                2.13.96              ha180cfb_0    conda-forge
        fonts-conda-ecosystem     1                             0    conda-forge
        fonts-conda-forge         1                             0    conda-forge
        fonttools                 4.29.1           py39h3811e60_0    conda-forge
        freetype                  2.10.4               h0708190_1    conda-forge
        fsspec                    2022.2.0           pyhd8ed1ab_0    conda-forge
        gettext                   0.19.8.1          h73d1719_1008    conda-forge
        giflib                    5.2.1                h36c2ea0_2    conda-forge
        greenlet                  1.1.2            py39he80948d_1    conda-forge
        gst-plugins-base          1.18.5               hf529b03_3    conda-forge
        gstreamer                 1.18.5               h9f60fe5_3    conda-forge
        gwcs                      0.17.1             pyhd8ed1ab_0    conda-forge
        hypothesis                6.39.3             pyhd8ed1ab_0    conda-forge
        icu                       69.1                 h9c3ff4c_0    conda-forge
        idna                      3.3                pyhd8ed1ab_0    conda-forge
        imagecodecs               2022.2.22        py39hf577088_0    conda-forge
        imageio                   2.16.1             pyhcf75d05_0    conda-forge
        importlib-metadata        4.11.2           py39hf3d152e_0    conda-forge
        importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
        iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
        ipykernel                 6.4.2            py39hef51801_0    conda-forge
        ipython                   7.32.0           py39hf3d152e_0    conda-forge
        ipython_genutils          0.2.0                      py_1    conda-forge
        ipywidgets                7.6.5              pyhd8ed1ab_0    conda-forge
        jbig                      2.1               h7f98852_2003    conda-forge
        jedi                      0.18.1           py39hf3d152e_0    conda-forge
        jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
        joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
        jpeg                      9e                   h7f98852_0    conda-forge
        json5                     0.9.5              pyh9f0ad1d_0    conda-forge
        jsonschema                4.4.0              pyhd8ed1ab_0    conda-forge
        jupyter                   1.0.0            py39hf3d152e_7    conda-forge
        jupyter_client            7.1.2              pyhd8ed1ab_0    conda-forge
        jupyter_console           6.4.3              pyhd8ed1ab_0    conda-forge
        jupyter_core              4.9.2            py39hf3d152e_0    conda-forge
        jupyter_server            1.13.2             pyhd8ed1ab_0    conda-forge
        jupyter_telemetry         0.1.0              pyhd8ed1ab_1    conda-forge
        jupyterhub                2.1.1                hd8ed1ab_0    conda-forge
        jupyterhub-base           2.1.1              pyhd8ed1ab_0    conda-forge
        jupyterlab                3.2.9              pyhd8ed1ab_0    conda-forge
        jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
        jupyterlab_server         2.10.3             pyhd8ed1ab_0    conda-forge
        jupyterlab_widgets        1.0.2              pyhd8ed1ab_0    conda-forge
        jxrlib                    1.1                  h7f98852_2    conda-forge
        keyutils                  1.6.1                h166bdaf_0    conda-forge
        kiwisolver                1.3.2            py39h1a9c180_1    conda-forge
        krb5                      1.19.2               h3790be6_4    conda-forge
        lcms2                     2.12                 hddcbb42_0    conda-forge
        ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
        lerc                      3.0                  h9c3ff4c_0    conda-forge
        libaec                    1.0.6                h9c3ff4c_0    conda-forge
        libarchive                3.5.2                hccf745f_1    conda-forge
        libavif                   0.9.3                h166bdaf_1    conda-forge
        libblas                   3.9.0           13_linux64_openblas    conda-forge
        libbrotlicommon           1.0.9                h7f98852_6    conda-forge
        libbrotlidec              1.0.9                h7f98852_6    conda-forge
        libbrotlienc              1.0.9                h7f98852_6    conda-forge
        libcblas                  3.9.0           13_linux64_openblas    conda-forge
        libclang                  13.0.1          default_hc23dcda_0    conda-forge
        libcurl                   7.81.0               h2574ce0_0    conda-forge
        libdeflate                1.10                 h7f98852_0    conda-forge
        libedit                   3.1.20191231         he28a2e2_2    conda-forge
        libev                     4.33                 h516909a_1    conda-forge
        libevent                  2.1.10               h9b69904_4    conda-forge
        libffi                    3.4.2                h7f98852_5    conda-forge
        libgcc-ng                 11.2.0              h1d223b6_12    conda-forge
        libgfortran-ng            11.2.0              h69a702a_13    conda-forge
        libgfortran5              11.2.0              h5c6108e_13    conda-forge
        libglib                   2.70.2               h174f98d_4    conda-forge
        libgomp                   11.2.0              h1d223b6_12    conda-forge
        libiconv                  1.16                 h516909a_0    conda-forge
        liblapack                 3.9.0           13_linux64_openblas    conda-forge
        libllvm13                 13.0.1               hf817b99_2    conda-forge
        libmamba                  0.22.1               h9c208ef_0    conda-forge
        libmambapy                0.22.1           py39h3216e65_0    conda-forge
        libnghttp2                1.47.0               h727a467_0    conda-forge
        libnsl                    2.0.0                h7f98852_0    conda-forge
        libogg                    1.3.4                h7f98852_1    conda-forge
        libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
        libopus                   1.3.1                h7f98852_1    conda-forge
        libpng                    1.6.37               h21135ba_2    conda-forge
        libpq                     14.2                 hd57d9b9_0    conda-forge
        libsodium                 1.0.18               h36c2ea0_1    conda-forge
        libsolv                   0.7.19               h780b84a_5    conda-forge
        libssh2                   1.10.0               ha56f1ee_2    conda-forge
        libstdcxx-ng              11.2.0              he4da1e4_12    conda-forge
        libtiff                   4.3.0                h542a066_3    conda-forge
        libuuid                   2.32.1            h7f98852_1000    conda-forge
        libuv                     1.43.0               h7f98852_0    conda-forge
        libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
        libwebp                   1.2.2                h3452ae3_0    conda-forge
        libwebp-base              1.2.2                h7f98852_1    conda-forge
        libxcb                    1.13              h7f98852_1004    conda-forge
        libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
        libxml2                   2.9.12               h885dcf4_1    conda-forge
        libzlib                   1.2.11            h36c2ea0_1013    conda-forge
        libzopfli                 1.0.3                h9c3ff4c_0    conda-forge
        locket                    0.2.0                      py_2    conda-forge
        lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
        lzo                       2.10              h516909a_1000    conda-forge
        mako                      1.1.6              pyhd8ed1ab_0    conda-forge
        mamba                     0.22.1           py39hfa8f2c8_0    conda-forge
        markupsafe                2.1.0            py39hb9d737c_0    conda-forge
        matplotlib                3.5.1            py39hf3d152e_0    conda-forge
        matplotlib-base           3.5.1            py39h2fa2bec_0    conda-forge
        matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
        mistune                   0.8.4           py39h3811e60_1005    conda-forge
        munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
        mypy_extensions           0.4.3            py39hf3d152e_4    conda-forge
        mysql-common              8.0.28               ha770c72_0    conda-forge
        mysql-libs                8.0.28               hfa10184_0    conda-forge
        nbclassic                 0.3.5              pyhd8ed1ab_0    conda-forge
        nbclient                  0.5.11             pyhd8ed1ab_0    conda-forge
        nbconvert                 5.6.1              pyhd8ed1ab_2    conda-forge
        nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
        nbgitpuller               1.0.2                    pypi_0    pypi
        nbgrader                  0.6.2            py39hf3d152e_1    conda-forge
        ncurses                   6.3                  h9c3ff4c_0    conda-forge
        nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge
        networkx                  2.7.1              pyhd8ed1ab_0    conda-forge
        nodejs                    17.4.0               h8ca31f7_0    conda-forge
        notebook                  6.4.8              pyha770c72_0    conda-forge
        nspr                      4.32                 h9c3ff4c_1    conda-forge
        nss                       3.74                 hb5efdd6_0    conda-forge
        numpy                     1.22.2           py39h91f2184_0    conda-forge
        oauthlib                  3.2.0              pyhd8ed1ab_0    conda-forge
        openjpeg                  2.4.0                hb52868f_1    conda-forge
        openssl                   1.1.1l               h7f98852_0    conda-forge
        packaging                 21.3               pyhd8ed1ab_0    conda-forge
        pamela                    1.0.0                      py_0    conda-forge
        pandas                    1.4.1            py39hde0f152_0    conda-forge
        pandoc                    2.17.1.1             ha770c72_0    conda-forge
        pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
        parso                     0.8.3              pyhd8ed1ab_0    conda-forge
        partd                     1.2.0              pyhd8ed1ab_0    conda-forge
        pathspec                  0.9.0              pyhd8ed1ab_0    conda-forge
        pcre                      8.45                 h9c3ff4c_0    conda-forge
        pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
        photutils                 1.3.0            py39hce5d2b2_1    conda-forge
        pickleshare               0.7.5                   py_1003    conda-forge
        pillow                    9.0.1            py39hae2aec6_2    conda-forge
        pip                       22.0.3             pyhd8ed1ab_0    conda-forge
        platformdirs              2.5.1              pyhd8ed1ab_0    conda-forge
        pluggy                    1.0.0            py39hf3d152e_2    conda-forge
        prometheus_client         0.13.1             pyhd8ed1ab_0    conda-forge
        prompt-toolkit            3.0.27             pyha770c72_0    conda-forge
        prompt_toolkit            3.0.27               hd8ed1ab_0    conda-forge
        psutil                    5.9.0            py39h3811e60_0    conda-forge
        pthread-stubs             0.4               h36c2ea0_1001    conda-forge
        ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
        pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
        py                        1.11.0             pyh6c4a22f_0    conda-forge
        pybind11-abi              4                    hd8ed1ab_3    conda-forge
        pycosat                   0.6.3           py39h3811e60_1009    conda-forge
        pycparser                 2.21               pyhd8ed1ab_0    conda-forge
        pycurl                    7.44.1           py39h72e3413_1    conda-forge
        pyerfa                    2.0.0.1          py39hce5d2b2_1    conda-forge
        pygments                  2.11.2             pyhd8ed1ab_0    conda-forge
        pyjwt                     2.3.0              pyhd8ed1ab_1    conda-forge
        pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
        pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
        pyqt                      5.12.3           py39hf3d152e_8    conda-forge
        pyqt-impl                 5.12.3           py39hde8b62d_8    conda-forge
        pyqt5-sip                 4.19.18          py39he80948d_8    conda-forge
        pyqtchart                 5.12             py39h0fcd23e_8    conda-forge
        pyqtwebengine             5.12.1           py39h0fcd23e_8    conda-forge
        pyrsistent                0.18.1           py39h3811e60_0    conda-forge
        pysocks                   1.7.1            py39hf3d152e_4    conda-forge
        pytest                    7.0.1            py39hf3d152e_0    conda-forge
        pytest-arraydiff          0.3                        py_0    conda-forge
        pytest-astropy            0.9.0              pyhd8ed1ab_0    conda-forge
        pytest-astropy-header     0.1.2                      py_0    conda-forge
        pytest-cov                3.0.0              pyhd8ed1ab_0    conda-forge
        pytest-doctestplus        0.12.0             pyhd8ed1ab_0    conda-forge
        pytest-filter-subpackage  0.1.1                      py_0    conda-forge
        pytest-mock               3.7.0              pyhd8ed1ab_0    conda-forge
        pytest-openfiles          0.5.0                      py_0    conda-forge
        pytest-remotedata         0.3.3              pyhd8ed1ab_0    conda-forge
        python                    3.9.10          h85951f9_2_cpython    conda-forge
        python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
        python-json-logger        2.0.1              pyh9f0ad1d_0    conda-forge
        python_abi                3.9                      2_cp39    conda-forge
        pytz                      2021.3             pyhd8ed1ab_0    conda-forge
        pywavelets                1.2.0            py39hce5d2b2_1    conda-forge
        pyyaml                    6.0              py39h3811e60_3    conda-forge
        pyzmq                     22.3.0           py39h37b5a0c_1    conda-forge
        qt                        5.12.9               ha98a1a1_5    conda-forge
        qtconsole                 5.2.2              pyhd8ed1ab_1    conda-forge
        qtconsole-base            5.2.2              pyhd8ed1ab_1    conda-forge
        qtpy                      2.0.1              pyhd8ed1ab_0    conda-forge
        rapidfuzz                 1.9.1            py39hde0f152_0    conda-forge
        readline                  8.1                  h46c0cb4_0    conda-forge
        reproc                    14.2.3               h7f98852_0    conda-forge
        reproc-cpp                14.2.3               h9c3ff4c_0    conda-forge
        requests                  2.27.1             pyhd8ed1ab_0    conda-forge
        ruamel.yaml               0.17.21          py39h3811e60_0    conda-forge
        ruamel.yaml.clib          0.2.6            py39h3811e60_0    conda-forge
        ruamel_yaml               0.15.80         py39h3811e60_1006    conda-forge
        scikit-image              0.19.2           py39hde0f152_0    conda-forge
        scikit-learn              1.0.2            py39h4dfa638_0    conda-forge
        scipy                     1.8.0            py39hee8e79c_1    conda-forge
        semantic_version          2.9.0              pyhd8ed1ab_0    conda-forge
        send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
        setuptools                60.9.3           py39hf3d152e_0    conda-forge
        six                       1.16.0             pyh6c4a22f_0    conda-forge
        snappy                    1.1.8                he1b5a44_3    conda-forge
        sniffio                   1.2.0            py39hf3d152e_2    conda-forge
        sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
        sqlalchemy                1.3.23           py39h3811e60_0    conda-forge
        sqlite                    3.37.0               h9cd32fc_0    conda-forge
        stack_data                0.2.0              pyhd8ed1ab_0    conda-forge
        terminado                 0.13.1           py39hf3d152e_0    conda-forge
        testpath                  0.6.0              pyhd8ed1ab_0    conda-forge
        threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
        tifffile                  2022.2.9           pyhd8ed1ab_0    conda-forge
        tk                        8.6.12               h27826a3_0    conda-forge
        toml                      0.10.2             pyhd8ed1ab_0    conda-forge
        tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
        toolz                     0.11.2             pyhd8ed1ab_0    conda-forge
        tornado                   6.1              py39h3811e60_2    conda-forge
        tqdm                      4.63.0             pyhd8ed1ab_0    conda-forge
        traitlets                 5.0.5                    pypi_0    pypi
        typed-ast                 1.5.2            py39h3811e60_0    conda-forge
        typing_extensions         4.1.1              pyha770c72_0    conda-forge
        tzdata                    2021e                he74cb21_0    conda-forge
        unicodedata2              14.0.0           py39h3811e60_0    conda-forge
        urllib3                   1.26.8             pyhd8ed1ab_1    conda-forge
        wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
        webencodings              0.5.1                      py_1    conda-forge
        websocket-client          1.3.1              pyhd8ed1ab_0    conda-forge
        wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
        widgetsnbextension        3.5.2            py39hf3d152e_1    conda-forge
        xorg-libxau               1.0.9                h7f98852_0    conda-forge
        xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
        xz                        5.2.5                h516909a_1    conda-forge
        yaml                      0.2.5                h7f98852_2    conda-forge
        yaml-cpp                  0.6.3                he1b5a44_4    conda-forge
        zeromq                    4.3.4                h9c3ff4c_1    conda-forge
        zfp                       0.5.5                h9c3ff4c_8    conda-forge
        zipp                      3.7.0              pyhd8ed1ab_1    conda-forge
        zlib                      1.2.11            h36c2ea0_1013    conda-forge
        zstd                      1.5.2                ha95c52a_0    conda-forge
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Jupyter never starts.  Here's the trace:
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-lab", line 6, in <module>
    from jupyterlab.labapp import main
  File "/opt/conda/lib/python3.9/site-packages/jupyterlab/labapp.py", line 15, in <module>
    from jupyter_server.serverapp import flags
  File "/opt/conda/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 83, in <module>
    from jupyter_server.services.sessions.sessionmanager import SessionManager
  File "/opt/conda/lib/python3.9/site-packages/jupyter_server/services/sessions/sessionmanager.py", line 22, in <module>
    from jupyter_server.traittypes import InstanceFromClasses
  File "/opt/conda/lib/python3.9/site-packages/jupyter_server/traittypes.py", line 7, in <module>
    from traitlets.utils.descriptions import describe
ModuleNotFoundError: No module named 'traitlets.utils.descriptions'
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
n/a
</pre>
</details>

**Comment by davidbrochart** [comment]
Thanks for reporting @vwbusguy.
Indeed it seems that `traitlets>=5` was required from v1.13.3, and you have v1.13.2. Upgrading should fix it, but you won't be able to install nbgrader.

**Comment by davidbrochart** [comment]
I don't have your exact environment, but I managed to install `jupyter_server=1.13.2` and `nbgrader` with conda, and `jupyter notebook` starts without error.

**Comment by vwbusguy** [comment]
I'm using the Jupyter docker image: jupyter/base-notebook:notebook-6.4.8 .  

Make sure the extension as also [enabled](https://nbgrader.readthedocs.io/en/stable/user_guide/installation.html#installing-and-activating-extensions):
```
jupyter nbextension install --sys-prefix --py nbgrader --overwrite
jupyter nbextension enable --sys-prefix --py nbgrader
jupyter serverextension enable --sys-prefix --py nbgrader
```

**Comment by blink1073** [comment]
This is coming from the conda-forge recipe being out of [sync](https://github.com/conda-forge/nbgrader-feedstock/blob/f445be50a0223c1b8cdfcd63bb3270e04a429a7f/recipe/meta.yaml#L38) with the dependencies.  I'm working on making a fix now.

**Comment by blink1073** [comment]
I merged the fix, it will take a while for the files to get to anaconda.org.  https://github.com/conda-forge/nbgrader-feedstock/pull/48
