### ISSUE TITLE
Passing pre_save_hook as importstring

### ISSUE THREAD

**Issue by dleen** [jupyter-server/jupyter_server#753]
## Description

Passing a `pre_save_hook` as an importstring e.g.
```
--FileContentsManager.pre_save_hook='mymodule.foo_function`
```

fails with the following error when launching the Jupyter server:
<details><summary>Troubleshoot Output</summary>
<pre>
    @validate("pre_save_hook")
    def _validate_pre_save_hook(self, proposal):
        value = proposal["value"]
        if isinstance(value, str):
            value = import_item(self.pre_save_hook)
        if not callable(value):
            raise TraitError("pre_save_hook must be callable")
        if self.pre_save_hook is not None:
            warnings.warn(
>               f"Overriding existing pre_save_hook ({self.pre_save_hook.__name__}) with a new one ({value.__name__}).",
                stacklevel=2,
            )
E           AttributeError: 'str' object has no attribute '__name__'
</pre>
</details>

If you edit `jupyter_server_config.py` to import the function, then setting the value is fine.

## Reproduce

Pass `pre_save_hook` or `post_save_hook` as a importstring.

## Expected behavior

Passing as a string or function works equally well.

## Discussion

The problem seems to be because the code assumes that `self.pre_save_hook` is always a function and has the `__name__` dunder.

**Comment by davidbrochart** [comment]
Thanks for opening an issue @dleen, I commented on the [PR](https://github.com/jupyter-server/jupyter_server/pull/754).
