### ISSUE TITLE
Switch to Flit Packaging Backend

### ISSUE THREAD

**Issue by blink1073** [jupyter-server/jupyter_server#796]
We can safely switch to the [`flit`](https://github.com/pypa/flit) packaging backend as long as we make sure we run `npm build` before publishing sdists and wheels.

I verified locally if you haven't run `npm build` the default pages served by Jupyter Server (`/`, `/logout`, and `/login`) will not have styling and will show 404 errors on the bootstrap assets.  We can make the npm steps optional for local development.

This change allows us to use a stable, PEP-compliant backend and not be concerned with the wider efforts `setuptools` is taking to absorb `distutils` and update its code-base for recent peps like editable installs.

We discussed this in the 21 Apr Server team meeting.  The server extension [cookiecutter](https://github.com/jupyter-server/extension-cookiecutter/pull/1) we started building during that meeting uses a flit backend.

**Comment by minrk** [comment]
👍 as long as we add tests for the wheel steps somewhere that catches the most likely failure (omitted npm artifacts). JupyterHub's wheel-building job [has this for a similar reason](https://github.com/jupyterhub/jupyterhub/blob/a588a0bfa39691793a6b8f788b112d8189179134/.github/workflows/release.yml#L55-L73).

**Comment by blink1073** [comment]
Oh nice, we could have a similar check in jupyter_releaser that uses importlib.resources and a list of expected files in the sdist/wheel.
