### ISSUE TITLE
New repo for shared documents

### ISSUE THREAD

**Issue by davidbrochart** [jupyter-server/jupyter_server#816]
### Problem

With the ongoing work in [JupyterLab around RTC](https://github.com/jupyterlab/jupyterlab/pull/12360), we are starting to create back-end [shared document structures](https://github.com/jupyterlab/jupyterlab/blob/c059bbc921dd66868bc457407ab8d3d938f78548/jupyterlab/handlers/ydoc.py) that shouldn't be tied to JupyterLab in particular. I can imagine e.g. a Python web client that would need these document structures as well, it shouldn't need to depend on JupyterLab.
We currently have:
- `class YFile(YBaseDoc)`: a document class for a generic text document.
- `class YNotebook(YBaseDoc)`: a document class for a notebook.

These classes currently have methods to:
- get initialized from a source (text/JSON).
- get exported to text/JSON.
- observe changes to the document.

### Proposed Solution

Maybe we could create a new repo in the `jupyter-server` organization, something like `ypy-documents`?

**Comment by ellisonbg** [comment]
David, thanks for working on this. I think it makes sense for this layer to be part of Jupyter server.

**Comment by echarles** [comment]
+1

**Comment by davidbrochart** [comment]
Maybe more things related to RTC will go in that new repo in the future. Also, maybe it shouldn't be so tied to the underlying technology (`Yjs`/`Ypy`)?
I was thinking about naming it `jupyter-rtc`, but it looks like you own it [on PyPI](https://pypi.org/project/jupyter-rtc/) @echarles ?

**Comment by echarles** [comment]
https://github.com/jupyter-rtc was to join home for the work we have been doing 1,5 year ago when we were still incepting on Automerge, Y.js... That could indeed be a place to expand any jupyter-rtc related work if we think it will grow beyond pure server aspects, which I think it will.

**Comment by echarles** [comment]
... I read too fast. You were referring on pypi. This was also a placeholder for the join work, so I can add you as admin to that package.

**Comment by davidbrochart** [comment]
Thanks Eric, I created https://github.com/davidbrochart/jupyter_ydoc, we can always transfer that repo to `jupyter-server` later.

**Comment by davidbrochart** [comment]
@fcollonval mentioned that [jupyter_ydoc should be part of a Jupyter GitHub organization](https://github.com/jupyterlab/jupyterlab/pull/12360#discussion_r865594240), so I guess https://github.com/jupyter-server is the right place.
It's still in development but it already supports [jupyter_releaser](https://github.com/davidbrochart/jupyter_releaser).
Is everyone okay with transferring the repo here?

**Comment by davidbrochart** [comment]
The repo has been created: https://github.com/jupyter-server/jupyter_ydoc.
