### ISSUE TITLE
Running file: uri path to use

### ISSUE THREAD

**Issue by vidartf** [jupyter-server/jupyter_server#83]
If giving the server launch command a file path, it will try to open the browser at `/notebooks/<file path>`:

https://github.com/jupyter/jupyter_server/blob/4b8c9eebfcae24f4a09fcb796fbcfb1fa27a2950/jupyter_server/serverapp.py#L1580

The `/notebooks` part should probably be configurable (for user and/or extension apps).

If that is agreed, then comes the bike shed that is what to call the trait. A first suggestion could be `file_to_run_url`, but I'm happy for better suggestions.

**Comment by Zsailer** [comment]
You're right. This should be configurable.

**Comment by blink1073** [comment]
This was handled by https://github.com/jupyter-server/jupyter_server/pull/415
