### ISSUE TITLE
traitlets 5.2 breaks --help-all check in application CLI

### ISSUE THREAD

**Issue by Zsailer** [jupyter-server/jupyter_server#843]
CI in #820 is failing at the `test_help_output` step, caused (I believe) https://github.com/ipython/traitlets/pull/698. 

We may need to temporarily pin traitlets to <5.2 to avoid blocking other PRs from merging until this issue can be solved. 

Related issue in traitlets. https://github.com/ipython/traitlets/issues/722

**Comment by blink1073** [comment]
Fixed by https://github.com/ipython/traitlets/pull/727
