### ISSUE TITLE
Printing emojis breaks the kernel

### ISSUE THREAD

**Issue by echarles** [jupyter-server/jupyter_server#857]
## Description

Printing an emoji breaks the kernel with jupyter-server HEAD. It was working with former version of jupyter-server (9 months ago).

## Reproduce

Run `print("😍")` in a notebook and get the following error.

```
W 2022-05-26 12:08:30.762 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x10731d6d0>
[IPKernelApp] ERROR | Invalid Message
Traceback (most recent call last):
  File "/Users/echarles/opt/miniconda3/envs/datalayer/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 359, in dispatch_shell
  File "/Users/echarles/opt/miniconda3/envs/datalayer/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 359, in dispatch_shell
    msg = self.session.deserialize(msg, content=True, copy=False)
  File "/Users/echarles/opt/miniconda3/envs/datalayer/lib/python3.9/site-packages/jupyter_client/session.py", line 1066, in deserialize
    message["content"] = self.unpack(msg_list[4])
  File "/Users/echarles/opt/miniconda3/envs/datalayer/lib/python3.9/site-packages/jupyter_client/session.py", line 127, in json_unpacker
    return json.loads(s)
  File "/Users/echarles/opt/miniconda3/envs/datalayer/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/echarles/opt/miniconda3/envs/datalayer/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/echarles/opt/miniconda3/envs/datalayer/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 107 (char 106)

</details>

**Comment by kevin-bates** [comment]
Hi @echarles.  This _may_ be related to some JSON changes in jupyter_client.  These were introduced in [7.0.6](https://github.com/jupyter/jupyter_client/releases/tag/v7.0.6) about 7 months ago.  Unfortunately, I believe the floor dependency on jupyter_client requires newer releases but it might make for a good data point if you can get some combination configured where only the version of juptyer_client reproduces the issue.

**Comment by echarles** [comment]
Thx @kevin-bates I will try to downgrade jupyter_client to confirm if this fixes the issue. I think however yesterday I tried with the same jupyter_client version, and changing jupyter_server version only were giving the issue. Let me check.

**Comment by echarles** [comment]
@kevin-bates I have downgraded both jupyter_client and ipykernel without luck. I also see similar errors when I try to load a pandas dataset from http, it makes me sense to encoding issue.

Before going further, could you confirm you are also having the same error running `print("✅")` in jupyterlab with the latest jupyter-server main branch installed?

I wonder if the recent changes to the processing of the ZMQ message can be the origin of that issue. 

cc/ @davidbrochart

**Comment by davidbrochart** [comment]
I just tried with JupyterLab 3.4.2 and jupyter-server HEAD, and it works fine. Could you post the output of `pip freeze`?

**Comment by kevin-bates** [comment]
@echarles thanks for checking this. I'm AFK until next Wednesday so am unable to help look into things more closely.

**Comment by echarles** [comment]
@davidbrochart @kevin-bates I have tested in a fresh env, and indeed it works fine.

I leave this open a bit more while investigating what may cause that issue in my other env. But looks like all good with jupyter-server and that is the issue is on my side. Thx again.

**Comment by echarles** [comment]
> I'm AFK until next Wednesday so am unable to help look into things more closely.

@kevin-bates Have a good time off. Thx!

**Comment by echarles** [comment]
@davidbrochart I have upgrade `jupyterlab` from `3.4.2` to `4.0.0a25` and now the issue arise on my fresh env.

Could you try on your side? Thx!

**Comment by davidbrochart** [comment]
Yes, I can reproduce with jupyter-server HEAD and jupyterlab v4.0.0a25.

**Comment by echarles** [comment]
so the next question is "how to identify the source of the issue: jupyter-server, jupyterlab, jupyterlab-server"?

**Comment by echarles** [comment]
As said, it is not only about emoji, I see the same errors loading some dataset in pandas.

**Comment by echarles** [comment]
Yes, it works also now with `ServerApp.kernel_ws_protocol=''`.

I had played with that setting, but was confused. You can give `None` or empty string, which is not fully readable to me.

**Comment by davidbrochart** [comment]
I opened https://github.com/jupyterlab/jupyterlab/pull/12619, it would be nice if you could check that it solved your issue @echarles.
For the `ServerApp.kernel_ws_protocol` setting, `''` will select the legacy protocol, and `None` will let the back-end and the front-end negotiate.

**Comment by echarles** [comment]
Thx @davidbrochart. I have a case where I don't use at all jupyterlab to execute code by the kernel hosted by jupyter-server. You have opened a fix on jupyterlab which sounds like it will not help my case, and potential other cases that simply use the server and kernels without juptyerlab. 

Is there a way to get a fix in server?

**Comment by echarles** [comment]
> For the ServerApp.kernel_ws_protocol setting, '' will select the legacy protocol, and None will let the back-end and the front-end negotiate.

I would prefer having words that say what the protocol is: `decompress` vs `transparent` and some docs (I am sure we can find better names that represent what the protocol effectively does)

**Comment by davidbrochart** [comment]
> Is there a way to get a fix in server?

The bug was in the front-end, the server was fine. If you still see an issue, I would need to reproduce it. Could you share your environment?

> I would prefer having words that say what the protocol is: decompress vs transparent and some docs

PR welcome :smile:

**Comment by echarles** [comment]
> The bug was in the front-end, the server was fine. If you still see an issue, I would need to reproduce it. Could you share your environment?

True. I have tested and merged https://github.com/jupyterlab/jupyterlab/pull/12619

> PR welcome 😄

Yeah, I need to think a bit more for good names.

**Comment by davidbrochart** [comment]
> I need to think a bit more for good names.

`None` seems to me like a good default value when the user "doesn't care" and would like the best (i.e. latest) protocol to be used, depending on the capabilities of the back-end and the front-end.
Maybe we could rename `''`, since we treat this legacy protocol name as a [special case](https://github.com/jupyter-server/jupyter_server/blob/3e64fa5eef7fba9f8e17c30cec688254adf913bd/jupyter_server/base/zmqhandlers.py#L282-L283) anyway. What about `v0.kernel.websocket.jupyter.org`, since the current version is `v1`?

**Comment by echarles** [comment]
Maybe I am too "a-la-lettre", but having a preferred protocol being None sounds strange to me. e.g. the "preferred" traits in jupyter_server have values

https://github.com/jupyter-server/jupyter_server/blob/061d846fbd0cf2f0be50d12c4a15feffd3214774/jupyter_server/serverapp.py#L1640-L1645

Using the effective protocol values sounds like a good tradeoff.

Could we just replace `None` with `v1.kernel.websocket.jupyter.org`?

**Comment by echarles** [comment]
Sorry, I was meaning this example

https://github.com/jupyter-server/jupyter_server/blob/061d846fbd0cf2f0be50d12c4a15feffd3214774/jupyter_server/serverapp.py#L1677-L1684

**Comment by davidbrochart** [comment]
> Could we just replace `None` with `v1.kernel.websocket.jupyter.org`?

`None` means "I don't have a preferred protocol", and I let the front-end and the back-end negotiate the best one.
Hard-coding  `v1.kernel.websocket.jupyter.org` would change the meaning of the default value to "use `v1.kernel.websocket.jupyter.org` and if not possible fall-back to the legacy protocol". It will lead to a different behavior than above when/if we have a `v2.kernel.websocket.jupyter.org`.
