### ISSUE TITLE
Register new file types

### ISSUE THREAD

**Issue by davidbrochart** [jupyter-server/jupyter_server#884]
### Problem

Currently, jupyter-server has the notion of file [type](https://github.com/jupyter-server/jupyter_server/blob/7b5815e0176c079d17c539c3baf6b497197f58a7/jupyter_server/services/contents/handlers.py#L101), which is hard-coded to either `"directory"`, `"file"` or `"notebook"`. Any other type would be treated as invalid.
In [jupyter-ydoc](https://github.com/jupyter-server/jupyter_ydoc) we have introduced the notion of Y document type. Current built-in types are [YFile](https://github.com/jupyter-server/jupyter_ydoc/blob/fdace934d7a1fb4d1590672919565d033dfc5bfb/jupyter_ydoc/ydoc.py#L50) and [YNotebook](https://github.com/jupyter-server/jupyter_ydoc/blob/fdace934d7a1fb4d1590672919565d033dfc5bfb/jupyter_ydoc/ydoc.py#L76), which map to a `"file"` and a `"notebook"`, respectively. This mapping is extensible using [entry points](https://github.com/jupyter-server/jupyter_ydoc/blob/fdace934d7a1fb4d1590672919565d033dfc5bfb/setup.cfg#L35-L38).
So one can create new Y document types, but not jupyter-server document types. Say I have a new file type that I want to open with JupyterLab and want it to be collaborative, I can create a Y document for it but I won't have any other choice than have it seen as a jupyter-server `"file"`.

### Proposed Solution

I mostly have questions:
- Should we introduce an extension mechanism in jupyter-server, that would allow to register a new file type, similarly to what we've done in jupyter-ydoc?
- Should we only have `"directory"` and `"file"` in jupyter-server, and get rid of `"notebook"`? I know we validate notebook formats, but should it be the responsibility of the server?

### Additional context

@trungleduc's [PR](https://github.com/jupyterlab/jupyterlab/pull/12719).

**Comment by SylvainCorlay** [comment]
I think that for our use case, it should always be `file` - and the special casing of the notebook type should probably go away.

**Comment by davidbrochart** [comment]
I started the [NBectomy](https://github.com/jupyter-server/jupyter_server/pull/891) and could remove quite a lot of code while keeping JupyterLab functional.

**Comment by kevin-bates** [comment]
If we were to allow for the registration of _Type Handlers_ as **an attribute of the current `ContentsManager`** would this provide a way forward?   (Btw, the _handler_ portion of this name should have no implication to a typical REST API _handler_.)

Practically speaking, the job of the `ContentsManager` is to persist and retrieve content.  The `FileContentsManager` deals with content in the filesystem, `SQLContentsManager` deals with content in a SQL DB, etc.  In all cases, notebooks are merely a file with two exceptions: 1. they are more rigidly validated, 2. they are checked relative to "trust" (kinda hand waving on that statement, but you get the idea).  However, their _persistence_ and _retrieval_ are identical to `"file"`.

If we let _Type Handlers_ deal with those aspects of the "content" where the file type in the model identifies which `TypeHandler` to perform that action with, then perhaps we have a way forward.  OOTB, Server would provide a `NotebookTypeHandler` but applications like RTC that perform "validation" and "trust" could unset or ignore `NotebookTypeHandler` or register their own instead.  (I haven't really thought through how this machinery would look, so, more hand-waving.)

Types that are not `"directory"` or `"file"` and do not have a registered _TypeHandler_ would be treated as `"file"`.  (In fact, you could argue that "directory" is really a special kind of "file".) We could also support the ability to register type handlers for "file" and "directory", if we wanted (and, again, providing defaults OOTB).

I'm not sure if this has any synergy to what has been done in RTC and I apologize for not following that more closely.

**Comment by davidbrochart** [comment]
Thanks Kevin, I think this is exactly what we need if we want to register new file type handlers.

**Comment by vidartf** [comment]
Does the merge of #895 close this, or are there still remaining tasks?

**Comment by davidbrochart** [comment]
I'll close it for now, we can re-open if we need to.

**Comment by a3626a** [comment]
I have found that custom file type is not allowed to be saved now.

`PUT /api/contents/path/Name.ipynb` does not change custom file type to 'file', while `GET` and `POST` do.
https://github.com/jupyter-server/jupyter_server/blob/4604ce0d8ba6fb92d08ec971d5571549b2cc9603/jupyter_server/services/contents/handlers.py#L231-L262

**Comment by davidbrochart** [comment]
Closing again, as #1013 was merged.
