### ISSUE TITLE
Please fix logging color on windows console

### ISSUE THREAD

**Issue by afshin** [jupyter-server/jupyter_server#943]
@char101 opened an [issue on JupyterLab](https://github.com/jupyterlab/jupyterlab/issues/12917) that seems like it is likely to be addressable in `jupyter_server`. What do you think? 

## Description

It seems that jupyter uses `tornado.log` for logging. In the comment of [tornado.log](https://github.com/tornadoweb/tornado/blob/master/tornado/log.py#L96) it is written

```
Color support on Windows versions that do not support ANSI color codes is
enabled by use of the colorama__ library. Applications that wish to use
this must first initialize colorama with a call to ``colorama.init``.
See the colorama documentation for details.
```

Unfortunately `colorama.init()` is never called by jupyter causing logging ANSI color to be output as raw escape codes.

## Reproduce

1. Run jupyter lab
2. Log shows raw ANSI escape sequences for color `←[2;32m[I 2022-08-07 18:50:14.236 ServerApp]←[0m`

## Expected behavior

Colored log in windows console.

## Context

- Operating System and version: Windows 10
- Browser and version: N/A
- JupyterLab version: 3.4.4

## Resolution

If possible please add `colorama.init()` in the main code

```python
try:
    import colorama
    colorama.init()
except ImportError:
    pass
```

cf. https://github.com/jupyterlab/jupyterlab/issues/12917

**Comment by kevin-bates** [comment]
@afshin - thank you for forwarding the issue here.  This makes sense.

@char101 - great write-up!  Is this a change you'd like to contribute?  I think the suggested change would simply go into the imports area of [`serverapp.py`](https://github.com/jupyter-server/jupyter_server/blob/main/jupyter_server/serverapp.py).  if this is something you'd rather defer to someone else, that's fine too.

**Comment by char101** [comment]
Since this is only a small change I would prefer to defer to someone else, thank you.
