### ISSUE TITLE
filemanger blocked when folder contains lots of files

### ISSUE THREAD

**Issue by eastonsuo** [jupyter-server/jupyter_server#964]
## Description

filemanger blocked when floder contains lots of files.

maybe we need a way to use page? instead of return all files all in once
<img width="965" alt="image" src="https://user-images.githubusercontent.com/12948621/188584813-8256008b-d74e-4b46-86fc-38ffc1040a70.png">

## Reproduce

create lots of files (may be more than 10k) in floder and open it

## Expected behavior

not block user behavior

## Context

- Operating System and version: mac/linux
- Browser and version:chrome
- Jupyter Server version:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by davidbrochart** [comment]
Hi @eastonsuo, an issue was opened about that in #962.

**Comment by Zsailer** [comment]
Closing in favor of #962
